eclipse/openvsx

- webui/src/pages/user/avatar.tsx
> [💄] a little bit of padding around the avatar menu.

- README.md
- cli/README.md
- Gitpod "ready-to-code" badge with logo
- NPM version badge
> Update README.md badges

- cli/README.md
It would also be cool to specify what OAuth scopes you need to grant, if any.
> Linkify "personal access token" for convenience

- webui/src/main.tsx
- webui/src/pages/extension-detail/extension-detail.tsx
- webui/src/pages/extension-list/extension-list-item.tsx
> add alt  text to the images.

- webui/src/pages/extension-list/extension-list-item.tsx
- webui/src/pages/extension-list/extension-list.tsx
Fixes eclipse/openvsx#51
This is how it looks:
> [extension-list] adjustments for small devices.

- webui/package.json
- webui/src/custom-mui-components/delayed-load-indicator.tsx
- webui/src/main.css
- webui/src/main.tsx
- webui/src/pages/extension-list/extension-list-container.tsx
- webui/src/pages/extension-list/extension-list-header.tsx
- webui/src/pages/extension-list/extension-list.tsx
- webui/src/pages/user/generate-token-dialog.tsx
- webui/yarn.lock
> Added infinite scroller behaviour to extension list

- cli/.gitignore
- cli/scripts/loadExampleData.js
- webui/src/pages/extension-list/extension-list-item.tsx
- webui/src/pages/extension-list/extension-list.tsx
Fixes eclipse/openvsx#53
Fixes eclipse/openvsx#54
> Items don't fade in slowly anymore, infinite loop  is prevented now

- webui/package.json
- webui/src/custom-mui-components/copy-to-clipboard.tsx
- webui/src/pages/user/generate-token-dialog.tsx
- webui/yarn.lock
Fixes #66
This is how it looks:
Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
> Generate new token dialog: Add 'copy to clipboard' button.

- webui/src/custom-mui-components/error-dialog.tsx
- webui/src/main.tsx
- webui/src/pages/extension-detail/extension-detail-overview.tsx
- webui/src/pages/extension-detail/extension-detail-reviews.tsx
- webui/src/pages/extension-detail/extension-detail.tsx
- webui/src/pages/extension-detail/extension-review-dialog.tsx
- webui/src/pages/extension-list/extension-list-container.tsx
- webui/src/pages/extension-list/extension-list.tsx
- webui/src/pages/user/avatar.tsx
- webui/src/pages/user/generate-token-dialog.tsx
- webui/src/pages/user/user-settings-tokens.tsx
- webui/src/pages/user/user-settings.tsx
- webui/src/utils.ts
This is how it looks : 
Fixes eclipse/openvsx#3
> [webui] add proper error handling.

- webui/dev/index.tsx
- webui/dev/static/index.html
- webui/src/main.css
- webui/src/main.tsx
- webui/src/page-settings.ts
- webui/src/pages/extension-list/extension-list-header.tsx
Fixes #81 
All the issues mentioned in the screenshot are resolved #81 apart from the ones related to colour contrast.
> [extension-list] small accessibility fixes

- webui/src/custom-mui-components/error-dialog.tsx
- webui/src/pages/extension-detail/extension-review-dialog.tsx
- webui/src/pages/user/generate-token-dialog.tsx
Fixes #85 
Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
> add Keyboard shortcuts for dialogs.

- webui/src/pages/extension-list/extension-list-container.tsx
- webui/src/pages/extension-list/extension-list-header.tsx
- webui/src/pages/extension-list/extension-list.tsx
> Shows number of results now.

- webui/dev/static/index.html
Hopefully this 
Fixes eclipse/openvsx#88
I had no problems in dev environment. So it's hard to test.
> Added charset meta tag

- webui/src/pages/extension-detail/extension-detail-reviews.tsx
- webui/src/pages/extension-detail/extension-review-dialog.tsx
This is how it looks:
Fixes eclipse/openvsx#79
> [extension-detail-reviews] adjust the layout for small devices.

- webui/dev/index.tsx
- webui/dev/page-settings.tsx
- webui/src/main.tsx
- webui/src/page-settings.ts
- webui/src/pages/extension-detail/extension-detail-overview.tsx
- webui/src/pages/extension-list/extension-list-header.tsx
I replaced most page settings with `React.FunctionComponent` so the web page can be well customized at the most important places.
> Make page better adaptable with FunctionComponents

- server/build.gradle
- server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java
- server/src/main/java/org/eclipse/openvsx/util/LicenseDetection.java
...for Apache-2.0, EPL-2.0, MIT, ISC, BSD-2-Clause, BSD-3-Clause
Fixes eclipse/openvsx#27
> Added license detection

- webui/src/extension-registry-types.ts
- webui/src/pages/user/user-namespace-extension-list-item.tsx
- webui/src/pages/user/user-namespace-extension-list.tsx
- webui/src/pages/user/user-settings-namespaces.tsx
- webui/src/pages/user/user-settings.tsx
> user-settings/namespaces: list extensions.

- webui/src/pages/extension-detail/extension-detail-overview.tsx
- webui/src/pages/extension-detail/extension-detail-tabs.tsx
- webui/src/pages/extension-list/extension-list-header.tsx
Just some grammar issues with a few things.
> Grammar fixes around the site.

- webui/package.json
- webui/src/pages/extension-detail/extension-detail-overview.tsx
> Added DOMPurify and sanitized readme text.

- server/src/main/java/org/eclipse/openvsx/IExtensionRegistry.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java
- server/src/main/java/org/eclipse/openvsx/search/SearchService.java
- webui/src/extension-registry-service.ts
- webui/src/extension-registry-types.ts
- webui/src/pages/extension-list/extension-list-container.tsx
- webui/src/pages/extension-list/extension-list-header.tsx
- webui/src/pages/extension-list/extension-list.tsx
Fixes https://github.com/eclipse/openvsx/issues/74
> Added ability to sort results.

- webui/dev/index.tsx
> Adapted backgroound for code blocks in details.

- webui/src/pages/extension-list/extension-list-container.tsx
- webui/src/pages/extension-list/extension-list-header.tsx
> Apply sortOrder and sortBy after reload

- server/src/main/java/org/eclipse/openvsx/IExtensionRegistry.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/FileResourceRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/search/SearchService.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAdapterTest.java
* Tweaked DB queries for better performance while gathering JSON output data
* Added parameter `includeAllVersions` to search endpoint (that data is not necessary in the web UI)
* Redirect to upstream registry files instead of piping file content
> Improved performance of search and extension queries

- server/src/main/java/org/eclipse/openvsx/AdminAPI.java
- server/src/main/java/org/eclipse/openvsx/AdminService.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/json/UserPublishInfoJson.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- webui/src/extension-registry-service.ts
- webui/src/extension-registry-types.ts
- webui/src/pages/admin-dashboard/admin-dashboard.tsx
- webui/src/pages/admin-dashboard/extension-admin.tsx
- webui/src/pages/admin-dashboard/namespace-admin.tsx
- webui/src/pages/admin-dashboard/namespace-input.tsx
- webui/src/pages/admin-dashboard/publisher-admin.tsx
- webui/src/pages/admin-dashboard/publisher-details.tsx
- webui/src/pages/admin-dashboard/publisher-revoke-dialog.tsx
- webui/src/pages/admin-dashboard/welcome.tsx
- webui/src/pages/user/user-extension-list.tsx
- webui/src/pages/user/user-namespace-extension-list-item.tsx
- webui/src/pages/user/user-namespace-extension-list.tsx
- webui/src/pages/user/user-settings-namespace-detail.tsx
- webui/src/pages/user/user-settings-profile.tsx
- webui/src/pages/user/user-settings.tsx
An operator/administrator shall be able to revoke a signed publisher agreement.
This functionality shall be accessible through an administration dashboard.
> Admin Dashboard: Publisher Administration

- webui/src/default/page-settings.tsx
- webui/src/default/theme.tsx
- webui/src/pages/extension-detail/extension-detail-overview.tsx
- webui/src/pages/extension-detail/extension-detail.tsx
> Fixed download button and footer link hover issue

- server/scripts/generate-properties.sh
- webui/src/default/page-settings.tsx
- webui/src/main.tsx
- webui/src/page-settings.ts
This is a preparation for https://github.com/eclipse/open-vsx.org/issues/171.
* The footer content component gets an `expanded` flag as input.
* Changed footer position to `fixed`.
* Changed footer color scheme to match the theme.
It is not mandatory to consider the `expanded` flag. The default UI does not consider it, but we'll expand the footer in https://github.com/eclipse/open-vsx.org
> Changed footer style, allow expanding the footer

- server/src/main/java/org/eclipse/openvsx/search/SearchConfig.java
Added support for custom truststore when using SSL connections to ElasticSearch.
> Custom SSLContext in SearchConfig

- server/src/main/java/org/eclipse/openvsx/search/SearchConfig.java
Prevents java.security.InvalidAlgorithmParameterException
> Set protocol on SSLContext 

- webui/src/default/default-app.tsx
Signed-off-by: Wang Liang <wangliang1@oppo.com>
> Added localhost port in dev environment

- webui/src/components/sanitized-markdown.tsx
Signed-off-by: Siddharth <siddharthmani2000@gmail.com>
Fixes: #207 Added CSS to the kbd tags
> Issue #207 : Styling of kbd tags

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
This PR adds cache headers to search and resource requests.
> [server] added caching to search and storage

- server/test-extensions.gradle
> Updated test extension versions

- server/src/main/resources/db/migration/V1_10__Foreignkey_Indexes.sql
This PR adds a migration with additional indexes on foreign keys.
> [db] added indexes for foreign keys

- server/.gitignore
- server/src/main/java/org/eclipse/openvsx/ExtensionService.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java
- server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java
- server/src/main/java/org/eclipse/openvsx/entities/ListOfStringConverter.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/resources/db/migration/V1_11__Denormalization.sql
> Denormalization of  db table `ExtensionVersion`

- server/build.gradle
> Bumping test dependency versions

- README.md
see https://github.com/eclipse/openvsx/issues/268#issuecomment-801747761
> clarify azure CORS setup

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
> Optimized cache-control max-age for certain fixed resources

- webui/src/pages/extension-list/extension-list-container.tsx
- webui/src/pages/extension-list/extension-list-header.tsx
- webui/src/pages/extension-list/extension-list.tsx
depending on whether submit the form by pressing Enter
or by typing the search token
Fixes eclipse/openvsx#273
> Set the debounce time for search dynamically

- .gitpod.yml
- cli/CHANGELOG.md
- cli/src/main.ts
- cli/src/publish.ts
- cli/src/registry.ts
- server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java
- server/src/main/java/org/eclipse/openvsx/ExtensionService.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/PublishOptions.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/adapter/ExtensionQueryResult.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java
- server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java
- server/src/main/java/org/eclipse/openvsx/entities/FileResource.java
- server/src/main/java/org/eclipse/openvsx/entities/ListOfStringConverter.java
- server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java
- server/src/main/java/org/eclipse/openvsx/repositories/FileResourceRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/main/resources/db/migration/V1_12__Extension_Kind.sql
- server/src/test/java/org/eclipse/openvsx/ExtensionProcessorTest.java
- server/test-extensions.gradle
**Note:** web extensions might need to be republished using the new `--web` parameter.
> Extension kind web

- cli/src/check-license.ts
See also https://github.com/halcyon-tech/git-client-ibmi/pull/1
> Also accept LICENCE files (alternative spelling)

- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
Fixes: #287
Contributes to: #266 
The following changes were made to the /api/-/query endpoint:
- Added GET method that accepts query parameters.
- Added deprecation notice to POST method.
- Added testcases for GET method.
- Renamed existing testcases for POST method.
>  Redundant calls for OPTIONS #287

- server/src/main/java/org/eclipse/openvsx/entities/Extension.java
- server/src/main/java/org/eclipse/openvsx/search/ExtensionSearch.java
- server/src/main/java/org/eclipse/openvsx/search/SearchService.java
> Added exact match search for namespace.name

- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
Fixes #285 
Changed queries to find bundled extensions and dependencies
>  [Admin] Server Error Removing Extension #285 

- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/main/java/org/eclipse/openvsx/web/SitemapController.java
Fixes #266
Added caching to more endpoints
Updated existing cache-control headers to be public
> Add more cache directives to the server #266

- README.md
- server/build.gradle
- server/scripts/generate-properties.sh
- server/src/main/java/org/eclipse/openvsx/RegistryApplication.java
- server/src/main/java/org/eclipse/openvsx/entities/AzureDownloadCountProcessedItem.java
- server/src/main/java/org/eclipse/openvsx/repositories/AzureDownloadCountProcessedItemRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/FileResourceRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/main/resources/db/migration/V1_15__Azure_Download_Count.sql
- server/src/test/java/org/eclipse/openvsx/AdminAPITest.java
- server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
- server/src/test/java/org/eclipse/openvsx/UserAPITest.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAdapterTest.java
- server/src/test/java/org/eclipse/openvsx/eclipse/EclipseServiceTest.java
Fixes #283
Added Azure download count scheduled task
Updated README.md
Make sure download isn't counted twice
>  Download Count seems off #283

- webui/src/components/sanitized-markdown.tsx
> Solves code overflow issue in markdown pages

- server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java
>  Internal server error while removing extension as admin #373 

- server/src/main/java/org/eclipse/openvsx/entities/Extension.java
- server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java
- server/src/main/java/org/eclipse/openvsx/entities/Namespace.java
- server/src/main/resources/db/migration/V1_20__ExtensionVersion_Deduplication.sql
Fixes #372
Fixes #374 
Add annotations to entities
Add unique constraints to entity and entity_version tables
Deduplicate entity, entity_version, file_resource and download tables
> Deduplicate ExtensionVersion and related entities

- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAdapterTest.java
- server/src/test/resources/org/eclipse/openvsx/adapter/findid-yaml-duplicate-query.json
- server/src/test/resources/org/eclipse/openvsx/adapter/findname-yaml-duplicate-query.json
> Extension query duplicate key IllegalStateException

- cli/CHANGELOG.md
- cli/package.json
- webui/package.json
- Fix repository not shown in npm.js
- Tidy up changelog
> Tidy up changelog

- server/src/main/java/org/eclipse/openvsx/util/UrlUtil.java
- server/src/test/java/org/eclipse/openvsx/util/UriUtilTest.java
Fixes https://github.com/eclipse/openvsx/issues/413
Change-Id: I200d5e1567118a026ac951389e616358cf81bba9
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
> feat: Add support for X-Forwarded-Prefix

- server/src/dev/resources/application.yml
- server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java
- server/src/main/java/org/eclipse/openvsx/RegistryApplication.java
- server/src/main/java/org/eclipse/openvsx/db/migration/V1_23__FileResource_Extract_Resources.java
- server/src/main/java/org/eclipse/openvsx/entities/Extension.java
- server/src/main/java/org/eclipse/openvsx/entities/FileResource.java
> Release 19286bf bugfix

- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionDTORepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java
- server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
- server/src/main/java/org/eclipse/openvsx/search/ISearchService.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAdapterTest.java
- server/src/test/resources/org/eclipse/openvsx/adapter/search-yaml-response-builtin-extensions.json
> Exclude built-in extensions

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/UserAPI.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/security/SecurityConfig.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/main/java/org/eclipse/openvsx/web/WebConfig.java
- server/src/test/java/org/eclipse/openvsx/UserAPITest.java
- webui/package.json
- webui/src/default/menu-content.tsx
- webui/src/default/theme.tsx
- webui/src/extension-registry-service.ts
- webui/src/main.tsx
- webui/src/pages/user/create-namespace-dialog.tsx
- webui/src/pages/user/publish-extension-dialog.tsx
- webui/src/pages/user/user-setting-tabs.tsx
- webui/src/pages/user/user-settings-extensions.tsx
- webui/src/pages/user/user-settings-namespace-detail.tsx
- webui/src/pages/user/user-settings-namespaces.tsx
- webui/src/pages/user/user-settings.tsx
- webui/src/server-request.ts
- webui/yarn.lock
Added publish button to header
Added extensions tab in user settings
Added ability to publish extension
Added ability to create namespace
Make namespaces visible for contributors
Testing steps:
A publish button has been added to the navigation menu.
Click the publish button, the rest of the UX should speak for itself.
> Do a manual (non-cli) upload

- server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java
- server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
- server/src/main/java/org/eclipse/openvsx/adapter/UpstreamVSCodeService.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java
Fixes #504
log upstream error, but return 404 not found.
> Ensure that failed requests to upstream are handled gracefully. #504

- cli/src/main.ts
- cli/src/publish.ts
- cli/src/util.ts
- cli/tsconfig.json
- server/build.gradle
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryApplication.java
Fixes #461
use allSettled in CLI, so that all publish processes finish
Make publish retryable
> Improve publishing using ovsx

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/dto/ExtensionVersionDTO.java
- server/src/main/java/org/eclipse/openvsx/dto/PersonalAccessTokenDTO.java
- server/src/main/java/org/eclipse/openvsx/dto/UserDataDTO.java
- server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionDTORepository.java
- server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
Fixes #474
- Publish extension using privileged user:
```
curl --location --request POST 'http://localhost:8080/api/-/publish?token=super_token' \
--header 'Content-Type: application/octet-stream' \
--data-binary '@<PATH_TO_VSIX>'
```
- JSON response `verified` field should be `true`
> Alter extension warning for super_user

- server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/dto/NamespaceDTO.java
- server/src/main/java/org/eclipse/openvsx/dto/UserDataDTO.java
- server/src/main/java/org/eclipse/openvsx/entities/AuthToken.java
- server/src/main/java/org/eclipse/openvsx/entities/EclipseData.java
- server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java
- server/src/main/java/org/eclipse/openvsx/search/ISearchService.java
- server/src/main/java/org/eclipse/openvsx/util/SemanticVersion.java
Regenerate hashCode and equals
Use equals instead of == when comparing ExtensionVersion or ExtensionVersionDTO
> Regenerate hashCode and equals

- server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
Add `@Transactional` annotation to `getAsset()` method
> Add @Transactional to getAsset()

- server/src/main/java/org/eclipse/openvsx/ExtensionService.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
- server/src/main/java/org/eclipse/openvsx/cache/CacheService.java
- server/src/main/java/org/eclipse/openvsx/cache/LatestExtensionVersionDTOCacheKeyGenerator.java
- server/src/main/java/org/eclipse/openvsx/util/VersionService.java
- server/src/test/java/org/eclipse/openvsx/util/VersionServiceTest.java
Fixes https://github.com/EclipseFdn/open-vsx.org/issues/1251
Fix cache key generator for ExtensionVersionDTO
> Platform-specific extensions cannot be found (HTTP 500) #1251

- webui/package.json
- webui/src/pages/extension-list/extension-list.tsx
- webui/src/server-request.ts
- webui/yarn.lock
Fixes #558
Use `fetch-retry` to retry failed requests with exponential backoff 
Only call infinite scroll loadMore function once
TODO remove if-statement in RegistryAPI.search before merging pull request
> fix /api/-/search endpoint call

- server/src/main/java/org/eclipse/openvsx/entities/SetPreReleaseMigrationItem.java
- server/src/main/java/org/eclipse/openvsx/migration/SetPreReleaseJobRequest.java
- server/src/main/java/org/eclipse/openvsx/migration/SetPreReleaseJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/SetPreReleaseMigration.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/repositories/SetPreReleaseMigrationItemRepository.java
- server/src/main/resources/db/migration/V1_26__Extension_Set_PreRelease.sql
> Set preRelease and preview for existing extensions

- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdService.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionHandler.java
Doesn't resolve #546, but is running in production.
> Update update existing public ids after getting public id from upstream

- server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
> Make ElasticSearch index and remove operations retryable

- server/src/main/java/org/eclipse/openvsx/storage/DownloadCountService.java
> Only update search entry when extension is active

- server/build.gradle
- server/src/main/java/org/eclipse/openvsx/RegistryApplication.java
- server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java
- server/src/test/java/org/eclipse/openvsx/AdminAPITest.java
- server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
- server/src/test/java/org/eclipse/openvsx/UserAPITest.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java
- server/src/test/java/org/eclipse/openvsx/eclipse/EclipseServiceTest.java
> Remove shedlock

- server/src/main/java/org/eclipse/openvsx/RegistryApplication.java
- server/src/main/java/org/eclipse/openvsx/web/InvalidMimeTypeExceptionHandler.java
Fixes #496 
Added global exception handler
> InvalidMimeTypeException handling

- server/src/dev/resources/application.yml
- server/src/gatling/scripts/test-registry-api.sh
- server/src/gatling/scripts/test-vscode-adapter.sh
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAPI.java
- server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
- server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountProcessor.java
- webui/src/pages/user/publish-extension-dialog.tsx
- webui/src/server-request.ts
Store max_result_window setting in variable to reduce lookups.
extensionquery merging improvements
Reset state of publish-extension-dialog after publish or cancel Only retry request on 5xx (Server Error).
Remove pauses between load tests
Uncomment all load tests
> Release 4651a66 improvements

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
Fixes #598
Add logging to get more info about this issue.
Add a null check.
> Download can't be found for some extension versions #598

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
Fixes #575
Removed filtering of web extensions
> Extensions that work for web only cannot be downloaded from webui #575

- server/src/main/java/org/eclipse/openvsx/AdminAPI.java
- server/src/main/java/org/eclipse/openvsx/AdminService.java
- server/src/main/java/org/eclipse/openvsx/entities/AdminStatistics.java
- server/src/main/java/org/eclipse/openvsx/json/AdminStatisticsJson.java
- server/src/main/java/org/eclipse/openvsx/repositories/AdminStatisticCalculationsRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/resources/db/migration/V1_27__AdminStatistics_More_Stats.sql
- server/src/test/java/org/eclipse/openvsx/AdminAPITest.java
Fixes #487
Get the results as JSON, in addition to CSV
Added extra statistics
> Make available additional information on activity

- webui/src/pages/user/add-namespace-member-dialog.tsx
Some JS code improvements to the <kbd>Add User to Namespace</kbd> dialog.
> Add member to namespace dialog improvements

- webui/src/pages/user/publish-extension-dialog.tsx
Fixes #615
Added error handling for invalid namespace name.
- Download [nitrous-vscode-color-theme-1.0.0.vsix.zip](https://github.com/eclipse/openvsx/files/10055384/nitrous-vscode-color-theme-1.0.0.vsix.zip)
- Remove `.zip` from the end of the file name
- Upload the vsix package through the webui
- You should get an error message: `Invalid namespace: undefined`
> Add error handling to webui extension publishing code

- server/src/test/java/org/eclipse/openvsx/repositories/PostgresDbRepositoryIntegrationTest.java
- server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
Fixes https://github.com/eclipse/openvsx/issues/371
> Quality: add repositories smoke test - github issue #371

- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAPI.java
Fixes #594
Use List instead of Map to preserve order
> improve search in VS Code

- .gitpod.yml
- server/test-extensions.gradle
Remove Equinusocio.vsc-material-theme-30.0.0.vsix because it is no longer available (404).
> Remove Equinusocio.vsc-material-theme-30.0.0.vsix

- cli/src/main.ts
- cli/src/publish.ts
> Feat: OVSX - Support skip if already published

- cli/CHANGELOG.md
- cli/package.json
Bump version and update CHANGELOG.md
> ovsx 0.8.0

- server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
Fixes #618
Use must and mustNot bool query clauses to filter results
> Can't search @category:"language packs" correctly in Code - OSS

- server/src/main/java/org/eclipse/openvsx/AdminService.java
- server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/UserAPI.java
- server/src/main/java/org/eclipse/openvsx/adapter/ExtensionQueryResult.java
- server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
- server/src/main/java/org/eclipse/openvsx/entities/FileResource.java
- server/src/main/java/org/eclipse/openvsx/migration/ExtractResourcesJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/ExtractResourcesJobService.java
- server/src/main/java/org/eclipse/openvsx/migration/ExtractVsixManifestsJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/MigrationRunner.java
- server/src/main/java/org/eclipse/openvsx/migration/MigrationService.java
- server/src/main/java/org/eclipse/openvsx/migration/RenameDownloadsJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/RenameDownloadsService.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/resources/db/migration/V1_32__FileResource_Extract_VsixManifest.sql
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java
- server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
- server/src/test/resources/org/eclipse/openvsx/adapter/findid-yaml-response-alpine.json
- server/src/test/resources/org/eclipse/openvsx/adapter/findid-yaml-response.json
- server/src/test/resources/org/eclipse/openvsx/adapter/findname-yaml-response-linux.json
- server/src/test/resources/org/eclipse/openvsx/adapter/findname-yaml-response.json
- server/src/test/resources/org/eclipse/openvsx/adapter/search-yaml-response-darwin.json
- server/src/test/resources/org/eclipse/openvsx/adapter/search-yaml-response-targets.json
- server/src/test/resources/org/eclipse/openvsx/adapter/search-yaml-response.json
> Missing VsixManifest asset type for extension versions

- server/src/main/java/org/eclipse/openvsx/AdminAPI.java
- server/src/main/java/org/eclipse/openvsx/entities/AdminStatistics.java
Fixes #653
Eager fetch ElementCollection in AdminStatistics
> https://open-vsx.org/admin/report API returning 500

- webui/package.json
- webui/src/page-settings.ts
- webui/src/pages/extension-detail/extension-detail-overview.tsx
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>
> Added download terms to page settings object, use in detailed overview

- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdService.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionHandler.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionService.java
Fixes #546
Update extension publicId of already published extensions when a new extension has the same publicId
> Insert unique extension public id

- server/src/main/java/org/eclipse/openvsx/migration/HandlerJobRequest.java
- server/src/main/java/org/eclipse/openvsx/migration/MigrationRunner.java
- server/src/main/java/org/eclipse/openvsx/migration/MigrationScheduler.java
- server/src/main/java/org/eclipse/openvsx/migration/MigrationService.java
Add possibility to delay running migrations, so that deployment can finish before migrations run
> Delay running migrations

- server/src/main/java/org/eclipse/openvsx/web/LongRunningRequestFilter.java
Create new StringBuilder to avoid concurrent access
> Create new StringBuilder

- server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java
- server/src/main/java/org/eclipse/openvsx/UserService.java
- webui/src/pages/user/user-namespace-details.tsx
Fixes #689
Set logoBytes before storing it
Improve social links UX
> Unable to update namespace details

- server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java
- server/src/main/java/org/eclipse/openvsx/UserService.java
- server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/IStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
Fixes #695
Get icon from storage
Use timestamp in namespace logo to bust browser cache
> Unable to delete namespace logo

- server/src/main/java/org/eclipse/openvsx/IExtensionRegistry.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java
- server/src/main/java/org/eclipse/openvsx/json/QueryParamJson.java
- server/src/main/java/org/eclipse/openvsx/json/QueryRequest.java
- server/src/main/java/org/eclipse/openvsx/json/QueryRequestV2.java
- server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
> Deprecate `/api/-/query` POST endpoint

- server/src/main/java/org/eclipse/openvsx/UserService.java
- server/src/test/java/org/eclipse/openvsx/UserAPITest.java
> Delete access token not allowed to load tokens

- doc/development.md
Hello,
I have written a setup guide on how to deploy OpenVSX on the local WSL environment before in #535.
Now I managed to deploy it on MacOS as well, so I recorded my way of doing it and modified my previous setup guide. Hopefully, this can help others a bit at least on the setup part.
Thank you :)
> add set up guide for MacOS

- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionService.java
> Merge ExtensionVersion before persisting FileResource

- server/src/main/java/org/eclipse/openvsx/admin/AdminAPI.java
- server/src/main/java/org/eclipse/openvsx/admin/AdminService.java
- server/src/main/java/org/eclipse/openvsx/admin/ChangeNamespaceJobRequest.java
- server/src/main/java/org/eclipse/openvsx/admin/ChangeNamespaceJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/admin/ChangeNamespaceService.java
- server/src/main/java/org/eclipse/openvsx/admin/RemoveFileJobRequest.java
- server/src/main/java/org/eclipse/openvsx/admin/RemoveFileJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/FixTargetPlatformsJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/mirror/DataMirrorJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/mirror/DataMirrorService.java
- server/src/test/java/org/eclipse/openvsx/admin/AdminAPITest.java
- server/src/test/java/org/eclipse/openvsx/cache/CacheServiceTest.java
Fixes #584
Remove files in background job
remove duplicate cache evict
>  Inefficient delete extension code? 

- server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java
- server/src/main/java/org/eclipse/openvsx/ExtensionService.java
- server/src/main/java/org/eclipse/openvsx/UserService.java
- server/src/main/java/org/eclipse/openvsx/migration/ExtractResourcesJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/ExtractVsixManifestsJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/FixTargetPlatformsJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/GenerateSha256ChecksumJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/MigrationService.java
- server/src/main/java/org/eclipse/openvsx/migration/RenameDownloadsJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/SetPreReleaseJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/SetPreReleaseJobService.java
- server/src/main/java/org/eclipse/openvsx/mirror/MirrorExtensionService.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionHandler.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionService.java
- server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java
- server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/IStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/main/java/org/eclipse/openvsx/util/TempFile.java
- server/src/test/java/org/eclipse/openvsx/ExtensionProcessorTest.java
Added AutoCloseable TempFile, so that a created file is always deleted after use.
> Use AutoCloseable TempFile

- server/src/main/java/org/eclipse/openvsx/cache/CacheService.java
- server/src/main/java/org/eclipse/openvsx/cache/LatestExtensionVersionCacheKeyGenerator.java
> Evict all latest extension versions

- cli/CHANGELOG.md
- cli/package.json
> Bump ovsx to 0.8.1

- server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java
- server/src/test/java/org/eclipse/openvsx/ExtensionValidatorTest.java
> Only check if host is not empty for http and https URLs

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java
- server/src/main/java/org/eclipse/openvsx/json/QueryParamJson.java
- server/src/main/java/org/eclipse/openvsx/json/QueryRequest.java
- server/src/main/java/org/eclipse/openvsx/json/QueryRequestV2.java
- server/src/main/java/org/eclipse/openvsx/json/QueryResultJson.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionJooqRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
- server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
Fixes #753 
Add paging to query endpoints
Merge query results
Add size and offset input validation
> Add paging to query endpoints

- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/resources/db/migration/V1_39__Fix_Unique_Constraints.sql
> Enforce implicit unique constraints in database

- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/web/ShallowEtagHeaderFilter.java
- webui/src/pages/extension-detail/extension-review-dialog.tsx
> Update review list right after user posting/revoking

- server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java
> Try load asset from extension.vsixmanifest

- server/build.gradle
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/admin/AdminAPI.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionHandler.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionService.java
Fixes #739
Fixes #764
Fixes #779 
Remove transactional from LocalRegistryService.publish
Remove merge when persisting file resource
> Error when publish the second version of the same extension

- server/build.gradle
- server/src/gatling/resources/gatling.conf
> Exclude gatling-charts-highcharts

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/548
Add CODE_OF_CONDUCT.md
Add SECURITY.md
Link to CODE_OF_CONDUCT.md in CONTRIBUTING.md
> Add recommended files to the repo

- .github/workflows/main.yml
- .github/workflows/sonar.yml
- cli/package.json
- server/build.gradle
- sonar-project.properties
Enable build and test
Add JaCoCo for test coverage
> Add test coverage

- server/src/main/java/org/eclipse/openvsx/adapter/PublicIds.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdService.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdUpdateService.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeIdUpdateServiceTest.java
Remove locking, has little effect for multiple Open VSX instances
Add extra unit tests
> Review public id updates

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionJooqRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
> Make versions endpoint case insensitive

- server/src/main/java/org/eclipse/openvsx/cache/CacheService.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionService.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionJooqRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/web/SitemapController.java
- server/src/main/java/org/eclipse/openvsx/web/SitemapRow.java
- server/src/main/java/org/eclipse/openvsx/web/SitemapService.java
- server/src/main/resources/ehcache.xml
- server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
> Optimize Sitemap

- server/src/main/java/org/eclipse/openvsx/IExtensionRegistry.java
- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java
- server/src/main/java/org/eclipse/openvsx/cache/ExtensionJsonCacheKeyGenerator.java
- server/src/main/java/org/eclipse/openvsx/cache/LatestExtensionVersionCacheKeyGenerator.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionJooqRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/FileResourceJooqRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/NamespaceMembershipJooqRepository.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java
- server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
- server/src/main/java/org/eclipse/openvsx/search/ISearchService.java
- server/src/main/java/org/eclipse/openvsx/search/SearchUtilService.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/main/java/org/eclipse/openvsx/util/VersionService.java
Add observation for `/api/{namespace}/{extension}/{targetPlatform}` 
Add observation for `/api/{namespace}/{extension}/{targetPlatform}/{version}` 
Remove observation for `/api/-/search`
Remove observation for `/api/-/query`
Remove observation for `/api/v2/-/query`
> Change observed endpoints

- cli/CHANGELOG.md
- cli/package.json
- cli/src/ovsx
- cli/yarn.lock
Update semver
Update @vscode/vsce
Regenerate yarn.lock
> Update semver to fix security vulnerability

- server/build.gradle
- server/src/main/java/org/eclipse/openvsx/security/TokenService.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageMigration.java
Fixes #856 
- Remove Google guava
- Remove SPDX tools
- Update bouncycastle to fix CVE-2023-33201
- Update Google cloud to fix CVE-2023-2976
- Add constraint on Eclipse parsson to fix CVE-2023-4043
> Fix server vulnerabilities

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/java/org/eclipse/openvsx/json/SearchEntryJson.java
> Add verified field to search results

- cli/src/get.ts
- cli/src/publish.ts
- cli/src/registry.ts
- webui/src/components/sidepanel/navigation-item.tsx
- webui/src/pages/admin-dashboard/publisher-admin.tsx
- webui/src/pages/admin-dashboard/publisher-revoke-dialog.tsx
- webui/src/pages/user/user-namespace-extension-list-item.tsx
- webui/src/pages/user/user-publisher-agreement.tsx
Use an optional chain expression, as it's more concise and easier to read.
> Use optional chain expression

- cli/src/registry.ts
- cli/src/util.ts
- webui/src/pages/extension-detail/extension-detail.tsx
- webui/src/pages/extension-list/extension-list-container.tsx
- webui/src/pages/namespace-detail/namespace-detail.tsx
- webui/src/pages/user/user-namespace-details.tsx
- webui/src/utils.ts
Prefer using nullish coalescing operator (`??`) instead of a logical or (`||`), as it is a safer operator.
> Use nullish coalescing

- .github/workflows/playwright.yml
- webui/.gitignore
- webui/configs/mocharc.json
- webui/configs/playwright.config.ts
- webui/configs/smoke-test.options.ts
- webui/package.json
- webui/test/e2e/README.md
- webui/test/e2e/smoke-test.spec.ts
- webui/test/unit/utils.spec.ts
- webui/yarn.lock
The tests ensure the following core features:
* **Main Page Navigation**: Confirming the visibility of extensions on the homepage.
* **Scroll Validation**: Scrolling to validate the dynamic loading of additional extensions.
* **Search Functionality**: Testing search inputs and category filters validating the changing results.
* **Extension Details**: Verifying the presence of specific extension details, including title, tabs, download counts, and version selection.
* **Direct Download**: Ensuring the successful download of extensions.
A Github workflow has been added to schedule a daily run against the production site at open-vsx.org.
> Add smoke tests

- webui/src/components/banner.tsx
> Fix banner double button

- server/src/main/java/org/eclipse/openvsx/migration/GenerateKeyPairJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/GenerateKeyPairJobService.java
- server/src/main/java/org/eclipse/openvsx/migration/MigrationScheduler.java
- server/src/main/java/org/eclipse/openvsx/publish/ExtensionVersionIntegrityService.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/main/java/org/eclipse/openvsx/repositories/SignatureKeyPairRepository.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageMigration.java
- server/src/test/java/org/eclipse/openvsx/publish/ExtensionVersionIntegrityServiceTest.java
- server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
Fixes #945 
- Prevent multiple active key pairs by deactivating all key pairs on renew
- Run migrations once per registry version
> Fix Internal Server Error on publish

- cli/src/get.ts
> Remove default universal for get operation

- server/build.gradle
- server/src/dev/resources/application.yml
- server/src/main/java/org/eclipse/openvsx/web/WebConfig.java
Try Jetty 12 for better throughput
Forward webui urls to /index.html
> Use Jetty Server

- server/build.gradle
Update to Spring Boot to v3.2.4 to fix https://github.com/jetty/jetty.project/issues/11095.
> Update Spring Boot to v3.2.4

- cli/CHANGELOG.md
- cli/package.json
- webui/package.json
> Release v0.16.4

- cli/CHANGELOG.md
- cli/package.json
- cli/yarn.lock
> ovsx 0.9.5

- .gitpod.dockerfile
- cli/package.json
- cli/src/create-namespace.ts
- cli/src/login.ts
- cli/src/logout.ts
- cli/src/main.ts
- cli/src/ovsx
- cli/src/publish.ts
- cli/src/store.ts
- cli/src/util.ts
- cli/src/verify-pat.ts
- cli/src/zip.ts
- cli/yarn.lock
Fixes #990 
- Get PAT from store
- Add login and logout commands
- Check node >= 20
- Gitpod set node to v20
> Add ovsx login equivalent to vsce login

- server/src/dev/resources/application.yml
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/adapter/ExtensionQueryParam.java
- server/src/main/java/org/eclipse/openvsx/adapter/ExtensionQueryResult.java
- server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAPI.java
- server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java
- server/src/main/java/org/eclipse/openvsx/json/QueryParamJson.java
- server/src/main/java/org/eclipse/openvsx/json/VersionReferenceJson.java
- server/src/main/java/org/eclipse/openvsx/web/DocumentationConfig.java
- Add API documentation to VSCodeAPI
- Diversify API examples
> VSCodeAPI documentation

- server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java
- server/src/test/java/org/eclipse/openvsx/MockTransactionTemplate.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java
Document why some methods are empty.
Use standard test matchers
> Document empty method body

- server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java
- Debug isNotOpenVSXUserAgent in AzureDownloadCountService 
- Remove tracing from AzureDownloadCountService
> Debug AzureDownloadCount userAgentHeader

- server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
Create new StreamingResponseBody for each response.
> Create new StreamingResponseBody

- server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
> Always include score when sorting

- server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java
- server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
- server/src/main/java/org/eclipse/openvsx/UserAPI.java
(Java) Reorder the modifiers to comply with the Java Language Specification.
> Java modifier order

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
Move replacement JSON to own method
- Less duplicated code
- Lowers cognitive complexity
> Move replacement JSON to own method

- server/src/main/java/org/eclipse/openvsx/extension_control/ExtensionControlService.java
Fixes #1110 
Also check if extension control is enabled when getting malicious extensions
> Check enabled malicious extensions

- server/src/main/java/org/eclipse/openvsx/migration/ScheduleMigrationsListener.java
- server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java
- server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
File resource jobs have completed
> Remove file resource job rescheduling

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
- server/src/main/resources/db/migration/V1_53__Deactivate_One_Time_Use_Publish_Token.sql
> Deactivate one time use publish token after extension publish

- server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java
- server/src/test/java/org/eclipse/openvsx/ExtensionValidatorTest.java
Fixes #826 
Allow zero width joiner unicode character to combine emojis.
> [Bug] Emoji is invalid

- server/src/main/java/org/eclipse/openvsx/publish/ExtensionVersionIntegrityService.java
Remove cache invalidation on application started event.
> Remove cache invalidation

- server/src/main/java/org/eclipse/openvsx/migration/CheckPotentiallyMaliciousExtensionVersionsService.java
Use regular logger in CheckPotentiallyMaliciousExtensionVersionsService
> Use regular logger

- server/build.gradle
- server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java
- server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
- server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
- server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java
Fixes #1171 
Update to Spring Boot 3.3.10 to update Spring Security to version 6.3.8.
> Fix CVE-2025-22228

- server/src/main/java/org/eclipse/openvsx/UserAPI.java
- server/src/main/java/org/eclipse/openvsx/eclipse/EclipseService.java
Use publisher agreement after signing instead of doing another API request.
> Use publisher agreement after signing

- .github/workflows/sonar.yml
`sonarsource/sonarcloud-github-action` is deprecated
> Update Sonar github action

- server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java
- server/src/main/java/org/eclipse/openvsx/ExtensionService.java
- server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java
- server/src/main/java/org/eclipse/openvsx/UserService.java
- server/src/main/java/org/eclipse/openvsx/entities/AuthTokenConverter.java
- server/src/main/java/org/eclipse/openvsx/entities/SemanticVersion.java
- server/src/main/java/org/eclipse/openvsx/migration/GenerateKeyPairJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/GenerateKeyPairJobService.java
- server/src/main/java/org/eclipse/openvsx/mirror/MirrorExtensionService.java
- server/src/main/java/org/eclipse/openvsx/publish/ExtensionVersionIntegrityService.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionHandler.java
- server/src/main/java/org/eclipse/openvsx/storage/AwsStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java
- server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/LocalStorageService.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageMigration.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/main/java/org/eclipse/openvsx/util/ErrorResultException.java
- server/src/main/java/org/eclipse/openvsx/web/SitemapController.java
- server/src/main/java/org/eclipse/openvsx/web/SitemapService.java
- server/src/test/java/org/eclipse/openvsx/entities/SemanticVersionTest.java
- server/src/test/java/org/eclipse/openvsx/publish/ExtensionVersionIntegrityServiceTest.java
Use more dedicated exceptions instead of RuntimeException
> Use dedicated exceptions

- server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
Don't use Stream.peek, because it's intended for debugging.
> Don't use Stream.peek

- server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdUpdateService.java
- server/src/main/java/org/eclipse/openvsx/eclipse/PublisherComplianceChecker.java
- server/src/main/java/org/eclipse/openvsx/extension_control/ExtensionControlJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/CheckPotentiallyMaliciousExtensionVersionsService.java
- server/src/main/java/org/eclipse/openvsx/migration/ExtensionVersionSignatureJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/ExtractVsixManifestsJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/FixTargetPlatformsJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/GenerateSha256ChecksumJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/MigrationService.java
- server/src/main/java/org/eclipse/openvsx/migration/PotentiallyMaliciousJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/RemoveFileResourceTypeResourceJobRequestHandler.java
- server/src/main/java/org/eclipse/openvsx/migration/SetPreReleaseJobService.java
- server/src/main/java/org/eclipse/openvsx/mirror/MirrorExtensionService.java
- server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionHandler.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageMigration.java
Use SLF4J fluent API with argument suppliers for log statements with heavy arguments (require extra computation).
> Use SLF4J fluent API

- cli/src/create-namespace-options.ts
- cli/src/create-namespace.ts
- cli/src/get-options.ts
- cli/src/get.ts
- cli/src/index.ts
- cli/src/login-options.ts
- cli/src/login.ts
- cli/src/publish-options.ts
- cli/src/publish.ts
- cli/src/registry-options.ts
- cli/src/registry.ts
- cli/src/util.ts
- cli/src/verify-pat-options.ts
- cli/src/verify-pat.ts
Split command and options interface to reduce circular dependencies.
> Split command and options

- cli/CHANGELOG.md
- cli/package.json
- server/src/main/java/org/eclipse/openvsx/admin/AdminAPI.java
- server/src/main/java/org/eclipse/openvsx/security/SecurityConfig.java
- server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
- server/src/main/java/org/eclipse/openvsx/web/DocumentationConfig.java
- server/src/test/java/org/eclipse/openvsx/admin/AdminAPITest.java
- webui/package.json
Reintroduce group to simplify diff
Update cli CHANGELOG
Add unit tests for Admin API token based endpoints
> v0.25.0-rc.1 changes

- server/src/main/java/org/eclipse/openvsx/migration/FixMissingFilesJobRequestHandler.java
- add logging
- return if no missing files
> Improve FixMissingFilesJobRequestHandler

- server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
ElasticSearch sort use _score for relevance
ElasticSearch query wrap text search in must block
> Improve search

- webui/package.json
- webui/src/pages/user/publish-extension-dialog.tsx
> webui: don't assume ErrorResult in tryResolveNamespaceError
