webui/src/pages/extension-detail/extension-detail-overview.tsx
Additionally the right detail area has an min-width of 290px now.
To try this out install https://open-vsx.org/extension/msjsdiag/debugger-for-chrome in dev environment.
Fixes eclipse/openvsx#42
=> code in markup gets wrapped now.

webui/src/pages/extension-list/extension-list-item.tsx
Fixes eclipse/openvsx#44
This is how it looks with the change in place:
I have used `rem` because It is better for accessibility:
According to W3: https://www.w3.org/WAI/tutorials/page-structure/styling/
=> Improve display of non-quadratic extension icons.

webui/dev/index.tsx, webui/src/pages/extension-list/extension-list-header.tsx
Fixes eclipse/openvsx#48
This is how it looks now:
=> [extension list] adjust the search to look good on mobile. 

webui/src/main.css, webui/src/pages/extension-detail/extension-detail-overview.tsx, webui/src/pages/extension-detail/extension-detail.tsx, webui/src/pages/extension-list/extension-list-item.tsx
Fixes #56 
This is how it looks now:
=> adjust [extension-detail] page for small devices.

webui/src/pages/user/user-setting-tabs.tsx, webui/src/pages/user/user-settings-profile.tsx, webui/src/pages/user/user-settings-tokens.tsx, webui/src/pages/user/user-settings.tsx
Fixes #71 #72
This is how it looks at mobile size:
tablet size:
Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
=> [user-settings] make user profile + tokens responsive for small devices.

webui/src/pages/extension-list/extension-list-item.tsx, webui/src/pages/extension-list/extension-list.tsx
Fixes #64 
This is how it looks with the change in place.
It is better than before but there are still some papers where the ellipsis is still there.
=> [extension-list-item] reduce the title font size.

webui/src/pages/extension-detail/extension-detail-overview.tsx
=> Use white-space: 'pre' instead of 'pre-line' for code tags now.

webui/src/pages/extension-detail/extension-detail-overview.tsx
test with https://open-vsx.org/extension/idleberg/applescript
code blocks have light grey background now
table is rendered correctly now
I had to remove 'commonmarks' which was the MarkupIt was instantiated with. Honestly I don't know why we had it in the first place. Please have a closer look in details/readme.
For me everything looks good. 
Fixes eclipse/openvsx#68
=> Fixed markup table issue and adapted several styles for readme

server/src/main/java/org/eclipse/openvsx/search/SearchService.java
When no extension is published and elasticsearch search, an error will occur
```json
{
"error":{
"root_cause":[
{
"type":"query_shard_exception",
"reason":"No mapping found for [relevance] in order to sort on",
"index_uuid":"QeBIwqzCQZ6rMtavW-WBVA",
"index":"extensions"
}
],
"type":"search_phase_execution_exception",
"reason":"all shards failed",
"phase":"dfs",
"grouped":true,
"failed_shards":[
{
"shard":0,
"index":"extensions",
"node":"-_gAqPHiTLObSesuEKIP7A",
"reason":{
"type":"query_shard_exception",
"reason":"No mapping found for [relevance] in order to sort on",
"index_uuid":"QeBIwqzCQZ6rMtavW-WBVA",
"index":"extensions"
}
}
]
},
"status":400
}
```
=> Fixed elasticsearch search error when no extension is published

webui/src/pages/user/user-settings-tokens.tsx
=> [user-setiings/tokens] align empty state text to the center.

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/UserService.java, server/src/main/java/org/eclipse/openvsx/entities/UserData.java, server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java, webui/dev/page-settings.tsx, webui/src/custom-mui-components/text-divider.tsx, webui/src/extension-registry-types.ts, webui/src/page-settings.ts, webui/src/pages/extension-detail/extension-detail-overview.tsx, webui/src/pages/extension-detail/extension-detail.tsx, webui/src/pages/extension-list/extension-list-item.tsx
This PR adds two things:
* A `privileged` user role that allows to publish to any namespace. We will use this for (any _only_ for) @open-vsx.
* Two kinds of banners for extension detail pages:
- namespace is public (it has no owner)
- namespace is restricted (it has an owner), but the extension was published by a user who is not related to that namespace (neither owner nor contributor)
The second case can happen if
* @open-vsx publishes to a restricted namespace with its privileged role.
* A user publishes to a public namespace and then a different user is granted ownership of that namespace.
* A contributor of a restricted namespace publishes an extension and then an owner removes her from that namespace via #96.
=> Privileged publishing, info banners for extensions

server/src/main/java/org/eclipse/openvsx/util/LicenseDetection.java, server/src/main/resources/spdx-templates/mit.txt, server/src/test/resources/org/eclipse/openvsx/util/MIT.txt, webui/yarn.lock
This PR enhances the license detection regarding MIT licenses. 
As an example the license of https://open-vsx.org/extension/ms-vscode/powershell-preview does not fit to MIT licenses because of too much quotation marks (which do not alter the semantics at all). 
This is identified as valid license now.
=> Enhanced License detection

cli/src/registry.ts, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java, server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java, server/src/main/java/org/eclipse/openvsx/json/SearchEntryJson.java, webui/src/extension-registry-types.ts, webui/src/pages/extension-detail/extension-review-dialog.tsx, webui/src/pages/extension-list/extension-list-item.tsx, webui/src/pages/extension-list/extension-list.tsx, webui/src/pages/user/user-setting-tabs.tsx
Fixes #140. I also adapted the existing `engines` field in the extension detail API for consistency.
=> Added 'allVersions' with engines map to search entries

.github/workflows/main.yml, server/Dockerfile
* Build the server within a container using a [multistage build](https://docs.docker.com/develop/develop-images/multistage-build/).
* Do not longer upload the raw `openvsx-server.jar` as GitHub action artifact
* Use the recommended `COPY` instead of `ADD` ([reference](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy))
Fixes #118
=> use multistage build to build open-vsx server

.github/workflows/main.yml, .gitpod.yml, server/Dockerfile, server/build.gradle, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java, server/src/main/java/org/eclipse/openvsx/search/SearchService.java, server/src/test/java/org/eclipse/openvsx/IntegrationTest.java, server/src/test/java/org/eclipse/openvsx/TestSearchConfig.java, server/src/test/resources/application.yml
This change adds a testcontainer for Elasticsearch so the search functionality can be included in the integration test.
=> Include Elasticsearch testcontainer for integration test

server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java, webui/src/pages/extension-detail/extension-detail.tsx
* In case an extension has not packaged its license, a link to the respective license page on [spdx.org](https://spdx.org/) is shown.
* Improved license detection when the license is given in the form `SEE MIT LICENSE IN LICENSE.md`, see for example [vscode-language-pack-de](https://github.com/microsoft/vscode-loc/blob/e81f98af158141ec32e25c22ec37b51945121eae/i18n/vscode-language-pack-de/package.json#L11) (currently rendered like [this](https://open-vsx.org/extension/MS-CEINTL/vscode-language-pack-de)).
=> Render license links to spdx.org, improved detection

README.md, cli/src/registry.ts, server/.gitignore, server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java, server/src/main/java/org/eclipse/openvsx/IExtensionRegistry.java, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/RegistryAPI.java, server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java, server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/json/QueryParamJson.java, server/src/main/java/org/eclipse/openvsx/json/QueryResultJson.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/NamespaceRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/security/SecurityConfig.java, server/src/main/java/org/eclipse/openvsx/util/ErrorResultException.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/UserAPITest.java, webui/package.json
Fixes #163.
* Most HTTP endpoints now return proper status codes in case of error (400 or 404).
* Endpoints related to extension metadata are left unchanged. These will be adapted after a few weeks so clients have time to migrate.
* Added a new endpoint `/api/-/query` that can be POSTed to get extension metadata. This is now the preferred endpoint for IDEs such as Theia. In case an extension is not found, it returns status 200 with an empty result.
=> More consistent status codes, added 'query' endpoint

.gitpod.yml, .vscode/launch.json, cli/src/check-license.ts, cli/src/publish.ts, cli/src/registry.ts, cli/src/util.ts, server/scripts/generate-properties.sh, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/eclipse/EclipseService.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/eclipse/EclipseServiceTest.java
This is a preparation for the upcoming transfer of open-vsx.org to the Eclipse Foundation. Extensions without license are going to be rejected.
The CLI offers to use the MIT license in case an extension is unlicensed. This is the output when the user denies this question:
```
$ ovsx publish
Extension namespace.name has no license. Would you like to publish it under the MIT license?
yes/[no]: No
❌  This extension cannot be accepted because it has no license.
```
And the output when the user accepts the change:
```
$ ovsx publish
Extension namespace.name has no license. Would you like to publish it under the MIT license?
yes/[no]: Yes
DONE  Packaged: /tmp/tmp-528018co4YOf55ycE.vsix (25 files, 1.7MB)
🚀  Published namespace.name v1.2.3
```
* Current users of the CLI are not affected by this …
=> Reject unlicensed extensions in default registry instance

webui/src/pages/admin-dashboard/extension-version-container.tsx, webui/src/pages/admin-dashboard/search-list-container.tsx
in admin dashboard for extension management there was a layout bug if the list of versions gets very long.
=> fixed css to respect long version lists in admin dashboard

cli/src/registry.ts, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/UserService.java, server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java, server/src/main/java/org/eclipse/openvsx/json/NamespaceJson.java, server/src/main/java/org/eclipse/openvsx/migration/OrphanNamespaceMigration.java, server/src/main/java/org/eclipse/openvsx/repositories/NamespaceRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, webui/src/extension-registry-types.ts, webui/src/pages/admin-dashboard/namespace-admin.tsx, webui/src/pages/extension-detail/extension-detail-overview.tsx, webui/src/pages/extension-detail/extension-detail.tsx, webui/src/pages/user/user-namespace-member-component.tsx, webui/src/pages/user/user-namespace-member-list.tsx, webui/src/pages/user/user-settings-namespace-detail.tsx, webui/src/pages/user/user-settings-namespaces.tsx
Fixes #217. This changes the handling of namespaces:
* Removed the concept of public namespaces: only members of a namespace can publish to it.
* When someone creates a namespace, they automatically become a contributor of that namespace.
* Extensions are shown as _verified_ in the UI if the publisher is a member of the namespace and the namespace has at least one owner. Otherwise the extensions are shown as _unverified_ with a warning icon and an explanatory banner.
Namespaces with no members are now called _orphaned_. There should be no orphaned namespaces, therefore a migration is executed on startup:
* All previous publishers to an orphaned namespace are added as contributors.
* Orphaned namespaces with no published extensions are deleted.
=> Implemented new namespace policy

server/src/main/java/org/eclipse/openvsx/search/SearchConfig.java
This makes the management.health.elasticsearch probe use the same
configuration as the HighLevelRestClient (which can't be done with
spring.elasticsearch.rest.* properties only). Without this, in some
cases (e.g. open-vsx.org), we would need to deactivate the elasticsearch
health probe.
See https://stackoverflow.com/a/55099492
=> Make an ES RestClient available in addition to HighLevelRestClient

server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java, server/src/main/java/org/eclipse/openvsx/util/ArchiveUtil.java, server/src/test/java/org/eclipse/openvsx/util/ArchiveUtilTest.java
Fixes #200. This is a follow-up of #230 that generalizes retrieval of default files (README, LICENSE, CHANGELOG) by ignoring case in their names.
=> Ignore case when finding default files

cli/src/check-license.ts, cli/src/index.ts, cli/src/publish.ts, cli/src/util.ts
Add **isLicenceOk** function to check the presence of licence, `validateManifest` function is exported as well to remove duplication [here](https://github.com/open-vsx/publish-extensions/blob/master/add-extension.js#L114)
There is described use case https://github.com/eclipse/openvsx/issues/222#issuecomment-759971119
**publish workflow behaviour is the same without any changes.**
=> refactor(cli): Update ./cli/check-licence.ts

server/src/main/java/org/eclipse/openvsx/eclipse/PublisherComplianceChecker.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/repositories/UserDataRepository.java
This PR adds an application startup task that can be enabled with the property `ovsx.eclipse.check-compliance-on-start`. It checks the Publisher Agreement status of all publishers and disables extension versions for which there is no active Publisher Agreement. This task should be run once after the grace period of the transition of open-vsx.org to the Eclipse Foundation has expired (January 9th, 2021). See [this blog post](https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry) for more details.
=> Implemented Publisher Agreement compliance check

cli/package.json, cli/src/check-license.ts, cli/yarn.lock
Following https://github.com/eclipse/openvsx/issues/240, I added a
simple CI check based on https://github.com/watson/is-ci.
While this adds another dependency to the project, this dependency has a
single one, and that one is dependency free.
I was initially looking into checking for a TTY (given https://github.com/actions/runner/issues/241), but this approach seems
more structured.
Hope it helps!
=> [cli] Skip license input when in a CI

server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
Towards #266, see [this comment](https://github.com/eclipse/openvsx/pull/271#pullrequestreview-617543160)
=> Reverted max-duration to 10m for resources with variable version.

webui/src/pages/extension-detail/extension-detail-overview.tsx
...showing the alias(es) of the selected version and/or links to other alias(es)
If the version is flagged as a preview this is generally shown in the version section behind the published date now.
Fixes eclipse/openvsx#270
=> Added an additional alias section

cli/CHANGELOG.md, cli/package.json, cli/yarn.lock
After the version update, the `ovsx` cli tool works fine. I tested the following scenarios:
I will merge this PR and publish the latest version to the staging area.
=> Updated vsce version

server/src/main/java/org/eclipse/openvsx/adapter/ExtensionQueryResult.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java, server/src/main/java/org/eclipse/openvsx/util/UrlUtil.java
Added web extension property to vscode adapter query result.
Fixes assetType spanning multiple path segments.
=> Web extension support fix

server/src/main/java/org/eclipse/openvsx/web/WebConfig.java
**Description**
Fixes: #289 
The following commit allows access to the `api` endpoint for all origins. Previously, the `api` endpoint was not accessible by `cors`
issues. The `"/api/*/*/review/**` remains protected (accessible only through the `webUI`).
I verified the changes (through gitpod) by making requests to the exposed server, and noticed that the headers were correctly set for the endpoint. I also verified that the other endpoints were still restricted to the `webUI`.
Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>
=> server: allow every origin to access api endpoint

README.md
See client code: https://github.com/gitpod-io/vscode/blob/622203104113eaf625d6b11837183b08109f7773/src/vs/workbench/services/extensionResourceLoader/browser/extensionResourceLoaderService.ts#L44-L58
=> [ature] add missing allowed headers to fetch web extensions

server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java, server/src/main/java/org/eclipse/openvsx/web/WebConfig.java
~~Explicitly instructs Spring to send CORS headers allowing any origin.~~
~~I haven't tested this, I'm not really a Java developer and am not set up to test this project. However I believe according to the Spring documentation that this will fix the issue at-hand.~~
Fixes #306 
I went ahead and set up a test environment, and as noted by daiyam below my original fix was insufficient as Spring already defaulted to all origins. On further investigation I found that the extensionquery endpoint was not covered by the pre-existing CORS mappings as defined in WebConfig.java, due to existing outside of the /api/ endpoint root. I've added two lines to add this endpoint to the CORS mappings, which in my quick test solved the issue.
=> #306 Send CORS headers so vscode can use the API

server/src/main/java/org/eclipse/openvsx/ExtensionService.java
python extensions bundles some proprietrary extensions via extension pack, so we fail to publish it. But bundled extensions are not mandatory, and bundling extension can function without it.
From https://code.visualstudio.com/api/references/extension-manifest#extension-packs: 
> An Extension Pack should not have any functional dependencies with its bundled extensions and the bundled extensions should be manageable independent of the pack. If an extension has a dependency on another extension, that dependency should be declared with the extensionDependencies attribute.
This PR removes a check that bundled extension must be published to Open VSX. And allow publishing of python extension which was broken otherwise for 10 months!
=> don't fail if bundled extension is missing, they are optional

webui/src/pages/extension-detail/extension-detail-overview.tsx
We should exclude internal tags from UI, they are used only for internal search by VS Code:
=> [webui] filter out internal tags

server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdService.java
We seen that in production public ides are not always persisted, leading to new ids on each query and breaking clients:  https://github.com/eclipse/openvsx/issues/317#issuecomment-900104912
This PR makes sure that the given entity state is merged in the current persistent context to be committed on the transaction end.
=> fix #317: make sure that public id gets persisted

server/src/main/java/org/eclipse/openvsx/entities/Download.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java, server/src/main/resources/db/migration/V1_17__Admin_Statistics_Handle_Delete.sql
Fixes #369 
Set `entity_active_state.active` to false when entity is deleted.
Decouple FileResource from Download.
Renamed table `download` column `file_resource_id` to `file_resource_id_not_fk` to make it clear it isn't a foreign key for future reference.
=> Handle entity deletes for admin statistics.

server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java
Fixes #380 
I've changed `blobClient.openInputStream()` to `blobClient.download`
I found this solution on StackOverflow relating to the Azure Blob Storage C# client SDK.
The AzureDownloadCountService uses similar method calls.
> Well, when you do a CloudBlob.OpenRead(), the client library is doing two operations.
> Attention to the ETag in the response.
> What happen if another WebRole do something in the blob between call? YES a race condition.
> Solution: Use CloudBlob.DownloadToStream(), that method only issues one call.
source: [https://stackoverflow.com/questions/5094089/azure-blob-the-condition-specified-using-http-conditional-headers-is-not-met](https://stackoverflow.com/questions/5094089/azure-blob-the-condition-specified-using-http-conditional-headers-is-not-met)
=> Download Count Broken #380

server/build.gradle, server/src/main/java/org/eclipse/openvsx/AdminService.java
Fixes https://github.com/EclipseFdn/open-vsx.org/issues/816
Added synchronization so that `Extension.latest` and `Extension.preview` aren't updated concurrently when deleting multiple extension versions at the same time.
=> Error Loading Extension Page because of removed versions #816

cli/package.json, cli/src/ovsx, cli/yarn.lock
I went through their release notes and found out that the only breaking change
that was documented is the minimum Node.js version requirement.
Also, vsce now uses semantic-release to automate their releasing process which
should help guarantee semver compliance from their side. Therefore, I'm loosing
the version constraint on the package.json file from `~` to `^` which allows
any `2.x.x` version of vsce to be used.
BREAKING CHANGE: Now the minimum supported Node.js version is v14.0.0.
Closes #400 and closes #401.
=> Bump vsce from 1.100.1 to 2.6.3

server/src/main/java/org/eclipse/openvsx/ExtensionService.java, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
[LocalRegistryService](https://github.com/eclipse/openvsx/blob/master/server/src/main/java/org/eclipse/openvsx/ExtensionService.java)
```java
@Transactional(TxType.REQUIRED)
public ExtensionVersion publishVersion(InputStream content, PersonalAccessToken token) {
try (var processor = new ExtensionProcessor(content)) {
// Extract extension metadata from its manifest
var extVersion = createExtensionVersion(processor, token.getUser(), token);
processor.getExtensionDependencies().forEach(dep -> addDependency(dep, extVersion));
processor.getBundledExtensions().forEach(dep -> addBundledExtension(dep, extVersion));
// Check the extension's license
var resources = processor.getResources(extVersion);
checkLicense(extVersion, resources);
// Update the 'latest' / 'preview' references and the search …
```
=> Fix data inconsistency between database and elasticsearch

server/build.gradle, server/src/main/java/org/eclipse/openvsx/AdminAPI.java, server/src/main/java/org/eclipse/openvsx/AdminService.java, server/src/test/java/org/eclipse/openvsx/AdminAPITest.java, webui/package.json, webui/src/extension-registry-service.ts, webui/src/pages/admin-dashboard/extension-remove-dialog.tsx
PR #396 tried to fix https://github.com/EclipseFdn/open-vsx.org/issues/816 by using a synchronized block. This approach doesn't work on the staging server.
I've changed the endpoint to delete all versions in one request, so that the versions are deleted one after another instead of deleted by multiple parallel requests. This does work on the staging server.
You can test this by publishing 3+ versions of the same extension and then deleting 2+ versions (keep 1 version) in the admin dashboard.
=> Delete all versions at once to prevent race condition

server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java
use Boolean, so that preRelease is only included in the response if it has been set.
=> use Boolean for ExtensionJson.preRelease

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/RegistryAPI.java, server/src/main/java/org/eclipse/openvsx/json/QueryParamJson.java
Fixes bug introduced by #357
`param.includeAllVersions` was only used here:
https://github.com/amvanbaren/openvsx/blob/181346853fe636cb171321a69a1a161f286dbd27/server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java#L269-L281
when `param.extensionVersion` is specified, then 
https://github.com/amvanbaren/openvsx/blob/181346853fe636cb171321a69a1a161f286dbd27/server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java#L242 
is called, skipping the `param.includeAllVersions` logic.
#357 changed this to 
https://github.com/amvanbaren/openvsx/blob/db776443c68abb08f6649ecaaa5c971d561099f8/server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java#L270
while it should skip this logic if `param.includeAllVersions` is specified.
Testing steps:
Call …
=> Ignore includeAllVersions if extensionVersion is specified.

server/src/main/java/org/eclipse/openvsx/ExtensionService.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java, server/src/test/java/org/eclipse/openvsx/AdminAPITest.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/eclipse/EclipseServiceTest.java
Set `extension.latest`, whether it's a pre-release or not. It fixes https://github.com/eclipse/openvsx/pull/410#issuecomment-1034831850
Testing steps:
- Create namespace
- Publish a pre-release version for a new extension.
- Check that latest_id points to the pre-release: `SELECT e.name, ev.version, ev.pre_release FROM extension e JOIN extension_version ev ON ev.id = e.latest_id`. On gitpod you can use the `psql` CLI tool to execute queries.
- Publish a newer regular version for the same extension, use the same query to verify that `latest` now points to the newer regular version.
- Finally, publish a newer pre-release version and again verify that `latest` points to the pre-release.
- Now you can also delete each version one at a time in reverse order and again check that `latest` is …
=> Set latest version, whether it's a pre-release or not

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/RegistryAPI.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java, server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java, server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java, server/src/main/java/org/eclipse/openvsx/util/UrlUtil.java, server/src/test/java/org/eclipse/openvsx/storage/AzureBlobStorageServiceTest.java, server/src/test/java/org/eclipse/openvsx/util/UriUtilTest.java
Fixes #426
Contributes to #432
Validation steps:
- to reproduce the error, use master branch. to test the fix use this branch
- open the branch in gitpod
- wait until publisher terminal is done executing its task
- use publisher terminal to execute the following commands:
- create namespace: 
```
curl --location --request POST 'http://localhost:8080/api/-/namespace/create?token=super_token' \
--header 'Content-Type: application/json' \
--data-raw '{"name":"abelfubu"}'
```
- download vsix package: 
```
curl --location --request GET 'https://open-vsx.org/api/abelfubu/abelfubu-dark/1.3.4/file/abelfubu.abelfubu-dark-1.3.4.vsix' \
--output 'abelfubu.abelfubu-dark-1.3.4.vsix'
```
- publish vsix package: 
```
curl --location --request POST 'http://localhost:8080/api/-/publish?token=super_token' …
```
=>  URI encode FileResource urls

server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java, server/src/main/java/org/eclipse/openvsx/db/migration/V1_23__FileResource_Extract_Resources.java, server/src/main/java/org/eclipse/openvsx/dto/FileResourceDTO.java, server/src/main/java/org/eclipse/openvsx/entities/FileResource.java, server/src/main/java/org/eclipse/openvsx/repositories/FileResourceDTORepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtil.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAdapterTest.java, server/src/test/resources/org/eclipse/openvsx/adapter/findid-yaml-response-alpine.json, server/src/test/resources/org/eclipse/openvsx/adapter/findid-yaml-response.json, server/src/test/resources/org/eclipse/openvsx/adapter/findname-yaml-response-linux.json, server/src/test/resources/org/eclipse/openvsx/adapter/findname-yaml-response.json, server/src/test/resources/org/eclipse/openvsx/adapter/search-yaml-response-darwin.json, server/src/test/resources/org/eclipse/openvsx/adapter/search-yaml-response-targets.json, server/src/test/resources/org/eclipse/openvsx/adapter/search-yaml-response.json
Fixes #432 
Added publisher displayName
Added `/vscode/unpkg` endpoint to VSCodeAdapter
Removed WEB_RESOURCE, instead use RESOURCE
FileResource java migration
Updated `/vscode/extensionquery` tests to include web resources
Added `/vscode/asset` tests for web resources
- Update VS Code product.json:
```
"extensionsGallery": {
"serviceUrl": "http://localhost:8080/vscode/gallery",
"itemUrl": "http://localhost:8080/vscode/item",
"resourceUrlTemplate": "http://localhost:8080/vscode/unpkg/{publisher}/{name}/{version}/{path}"
},
```
- Restart VS Code if it is running, to apply the changes to product.json
- Publish a couple extensions where the package.json returned 404:
- `viper-admin.viper 2.4.0`
- `huacat.office-theme 1.1.3`
- `PKief.material-product-icons 1.1.2`
- Open developer tools in VS …
=> Some extension resource url return 404 or 500

server/build.gradle, server/src/main/java/org/eclipse/openvsx/AdminService.java, server/src/main/java/org/eclipse/openvsx/ExtensionService.java, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/RegistryAPI.java, server/src/main/java/org/eclipse/openvsx/RegistryApplication.java, server/src/main/java/org/eclipse/openvsx/UserService.java, server/src/main/java/org/eclipse/openvsx/cache/CacheService.java, server/src/main/java/org/eclipse/openvsx/cache/ExtensionJsonCacheKeyGenerator.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java, server/src/main/java/org/eclipse/openvsx/util/TargetPlatform.java, server/src/main/java/org/eclipse/openvsx/web/ShallowEtagHeaderFilter.java, server/src/test/java/org/eclipse/openvsx/AdminAPITest.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/UserAPITest.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAdapterTest.java, server/src/test/java/org/eclipse/openvsx/cache/CacheServiceTest.java, server/src/test/java/org/eclipse/openvsx/eclipse/EclipseServiceTest.java
Fixes #391
Contributes to #379
The server uses a fixed caching strategy. `/api/{namespace}/{extension}` responses are cached for 10 minutes and `/api/{namespace}/{extension}/{version}` responses are cached for 7 days. When changing the version using the dropdown, the browser location changes to `/extension/{namespace}/{extension}/{version}`. If the version page has been visited before, the browser loads JSON from cache, else it sends a request to the API. Data inconsistencies emerge when some versions are loaded from cache while others are newly requested and the extension has been updated in the meantime (download count increase, version was added or removed, user details changed).
Instead of caching responses for a fixed duration, use Etag response header to always return the current …
=> Etag and caching

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAdapter.java, server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java, server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java, server/src/main/java/org/eclipse/openvsx/search/ISearchService.java, server/src/main/java/org/eclipse/openvsx/search/SearchUtilService.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAdapterTest.java, server/src/test/java/org/eclipse/openvsx/search/DatabaseSearchServiceTest.java, server/src/test/java/org/eclipse/openvsx/search/ElasticSearchServiceTest.java
Fixes #473
Throw exception when ElasticSearch result window is too large
Removed paging logic from LocalRegistryService.java
Added paging logic to ElasticSearchService.java
Only use PageRequest in ElasticSearchService.java
=> 503 on https://open-vsx.org/

.gitpod.yml
Because `gp await-port` was recently deprecated (https://github.com/gitpod-io/gitpod/pull/10463), this PR replaces it with the new command, `gp ports await`.
=> Use `gp ports await` instead of `gp await-port` in `.gitpod.yml`

server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java, server/src/main/java/org/eclipse/openvsx/adapter/IVSCodeService.java, server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java, server/src/main/java/org/eclipse/openvsx/adapter/UpstreamVSCodeService.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAPI.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java, webui/src/pages/extension-detail/extension-detail-overview.tsx
Fixes #417 
- Open this branch in Gitpod.
- Wait until the publisher process has published all test extensions.
- Stop the  server.
- Configure ovsx.upstream.url in dev/application.properties.
- Run the server: `./gradlew runServer`.
- Publish an extension that the upstream server also has.
- Publish an extension that the upstream server doesn't have.
Endpoints:
- `POST /vscode/gallery/extensionquery`
- `GET /vscode/asset/{namespace}/{extensionName}/{version}/{assetType}/**`
- `GET /vscode/item?itemName={itemName}`
- `GET /vscode/gallery/publishers/{namespace}/vsextensions/{extension}/{version}/vspackage`
- `GET /vscode/unpkg/{namespaceName}/{extensionName}/{version}/**`
Steps:
- Get a local item.
- Get an upstream item.
- Get a non-existent item.
- Test result merging by querying for an …
=> Add upstream for VSCodeAPI endpoints

cli/src/publish.ts
Use `extension.targetPlatform` instead of `options.target`.
The logging format follows the same pattern as other parts of the codebase:
https://github.com/eclipse/openvsx/blob/df28c16c4d919afaf1c8795ab0dfabd842ceb6e6/cli/src/get.ts#L106-L107
https://github.com/eclipse/openvsx/blob/df28c16c4d919afaf1c8795ab0dfabd842ceb6e6/server/src/main/java/org/eclipse/openvsx/ExtensionService.java#L190-L193
cc @radeksimko
=> Mention target in publish info message

server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java, server/src/test/java/org/eclipse/openvsx/search/ElasticSearchServiceTest.java
Fixes #501
Silently fail when offset + size is outside of ElasticSearch result window
=> UI code sends high number of requests to backend. #501

server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java, server/src/main/java/org/eclipse/openvsx/ExtensionService.java, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionJobRequest.java, server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionJobRequestHandler.java, server/src/test/java/org/eclipse/openvsx/AdminAPITest.java, server/src/test/java/org/eclipse/openvsx/IntegrationTest.java, server/src/test/java/org/eclipse/openvsx/JobRunrConfig.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/eclipse/EclipseServiceTest.java, server/src/test/resources/application.yml
Fixes #471
I did some Gatling testing to check if running `FileResource` processing in the background makes a difference in terms of performance and request throughput. Please note that these tests were done on my local development environment. The Open VSX server and Gatling were running on the same machine (which can cause interference). To confirm these findings it would be a good idea to test against the staging server.
Below are the results when only 1 extension is published at a time. The current (OLD) publishing process performs a bit better in this case.
```
== OLD =========================================================================
---- Global Information --------------------------------------------------------
> request count                                       1137 …
```
=> Do file resource processing via background job

server/src/main/java/org/eclipse/openvsx/util/UrlUtil.java, server/src/test/java/org/eclipse/openvsx/util/UrlUtilTest.java
Headers can be array values or be a single string with comma separated value
So when computing the host using `X-Forwarded-Host` it should use the first value and not the 'joined' list concatenate by a comma else it leads to invalid base URL
example:
```
https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers
Be careful when using these headers on the origin server, since they will contain more than one (comma-separated) value if the original request already contained one of these headers. For example, you can use %{X-Forwarded-For}i in the log format string of the origin server to log the original clients IP address, but you may get more than one address if the request passes through several proxies.
```
Fixes https://github.com/eclipse/openvsx/issues/498
Change-Id: …
=> fix: X-Forwarded-Host header can be array or comma separated list

server/test-extensions.gradle
Update test extensions to remove problematic Microsoft ones (due to licensing) and add the [Java extension by Redhat](https://open-vsx.org/extension/redhat/java) for testing platform-specific extensions.
=> Update test extensions

doc/development.md
Hi,
I am new to OpenVSX and I’ve spent some time deploying it to my local environment on WSL. During the process of setting it up myself, I encountered many problems.
I didn’t find detailed documentation on deploying OpenVSX with step-by-step instructions online, so I wrote down my process of setting it up in detail. I know that there must be multiple ways that can work, but hopefully, my experience can offer other beginners like me a bit of help at least.
=> Adding documentation on how to set up a local environment on WSL

server/src/main/java/org/eclipse/openvsx/entities/EclipseData.java
Fixes this exception:
```
Caused by: org.ehcache.spi.serialization.SerializerException: java.io.NotSerializableException: org.eclipse.openvsx.entities.EclipseData$PublisherAgreement
at org.ehcache.impl.serialization.PlainJavaSerializer.serialize(PlainJavaSerializer.java:51) ~[ehcache-3.10.0.jar:3.10.0]
at org.ehcache.impl.internal.store.offheap.portability.OffHeapValueHolderPortability.encode(OffHeapValueHolderPortability.java:52) ~[ehcache-3.10.0.jar:3.10.0]
at org.ehcache.impl.internal.store.offheap.portability.OffHeapValueHolderPortability.encode(OffHeapValueHolderPortability.java:32) ~[ehcache-3.10.0.jar:3.10.0]
... 152 common frames omitted
Caused by: java.io.NotSerializableException: org.eclipse.openvsx.entities.EclipseData$PublisherAgreement
at …
```
=> Make PublisherAgreement Serializable

server/src/main/java/org/eclipse/openvsx/AdminService.java, server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/PersonalAccessTokenRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/test/java/org/eclipse/openvsx/AdminAPITest.java, server/src/test/java/org/eclipse/openvsx/UserAPITest.java, webui/src/pages/user/user-extension-list.tsx
Fixes #599
Fix duplicate extension values in user dashboard
Fix duplicate extension values in admin publisher dashboard
- Stop the server.
- Assign the admin role to yourself: `UPDATE user_data SET role = 'admin' where login_name = <LOGIN_NAME>`.
- Restart the server.
- Publish multiple versions or multiple target platforms for the same extension.
- Navigate to `/user/extensions` in the webui.
- The extension you just published should only be displayed once.
- Navigate to `/admin-dashboard/publisher` and search for your login/publisher name.
- The extension you just published should only be displayed once.
=> User extensions view lists duplicate extension values in user dashboard

server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java, server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
Fixes #573
Return file if exact match is found
Exclude empty directory when processing resources
=>  vscode/unpkg route broken for assets #573 

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
Fixes #560 
Fix search result ordering in LocalRegistryService.java
Remove usage of deprecated withSort method in ElasticSearchService.java
- Open this PR in Gitpod, let the workspace initialize
- After all test extensions are published, stop the server
- Execute the `psql` command and update the extensions table:
```
UPDATE extension SET download_count = FLOOR(RANDOM() * 1000000 + 1);
```
- Then get extensions by download count:
```
SELECT n.name as namespace, e.name as extension, e.download_count
FROM extension e
JOIN namespace n ON n.id = e.namespace_id
ORDER BY e.download_count DESC;
```
- Restart the server
- Navigate to the Open VSX homepage
- Change the result order from `relevance` to `downloads`
- The result order must be equal to the SQL query
=> Sort by download count doesn't seem to be working correctly #560

webui/src/pages/extension-detail/extension-detail-overview.tsx
Fixes #595
Found this bug on http://open-vsx.org, in which in neither dark or light mode the links are visible. This PR fixes that.
| Before | After |
|---|---|
| <img width="257" alt="image" src="https://user-images.githubusercontent.com/29888641/202705663-83cbb700-174b-4e59-a77d-37cf4402dc95.png"> | <img width="312" alt="image" src="https://user-images.githubusercontent.com/29888641/202705602-aea13a98-c83d-4301-a59f-703671f526e0.png"> |
=> Fix color of extension detail view links

server/src/dev/resources/application.yml, server/src/main/java/org/eclipse/openvsx/web/SitemapController.java
Added `Content-Type` response header to SitemapController, so that the response is recognized as XML.
=> Set Content-Type application/xml for /sitemap.xml endpoint

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
Fixes #431
Added RegistryAPITest.testGetQueryExtensionVersion to replicate the issue.
- Download https://open-vsx.org/api/ms-python/python/2022.0.1814523869/file/ms-python.python-2022.0.1814523869.vsix.
- Download https://open-vsx.org/api/ms-python/python/2020.8.105369/file/ms-python.python-2020.8.105369.vsix.
- Create namespace `ms-python`.
- Publish the two downloaded extensions.
- Execute query: `curl --location --request GET 'http://localhost:8080/api/-/query?extensionId=ms-python.python&extensionVersion=2020.8.105369'`
- Expected result: a response containing `ms-python.python` version `2020.8.105369`.
=> Empty response for existing (old) plugin version

.vscode/extensions.json, cli/src/index.ts, cli/src/main.ts, cli/src/registry.ts, cli/src/verify-pat.ts, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/RegistryAPI.java, server/src/main/java/org/eclipse/openvsx/json/BadgeJson.java, server/src/main/java/org/eclipse/openvsx/json/ExtensionReferenceJson.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
Fixes #313
As https://github.com/eclipse/openvsx/issues/313 I got myself needing to verify the PAT before doing other steps down the road (e.g bumping the extension version) in continuous delivery, that is a pain to rollback etc. 
This PR proposes:
- A command in the ovsx set, called `verify-pat`, in which validates that certain token 1) is valid and 2) has publish access to a namespace
```bash
ovsx verify-pat namespace --pat my_pat
```
- An endpoint to support the `verify-pat` command, checking in the local registry the user's permission. If not conforming, the endpoint waits 2s to reply (but I'm in doubt that this is really necessary and beneficial)- the API also has rate limits, so a brute force to try tokens would not be fruitful anyway.
- Tests to support the endpoint. I could not …
=> Command to verify PAT

cli/CHANGELOG.md, cli/package.json, cli/src/main.ts, cli/src/publish.ts, cli/tsconfig.json, cli/yarn.lock
Fixes #634
Update `vsce` to `2.15.0`.
Turn of `noImplicitAny` to resolve: `error TS7016: Could not find a declaration file for module './publish'. implicitly has an 'any' type.`.
Pass `--no-dependencies` to `vsce`.
=> unknown option '--no-dependencies'

cli/CHANGELOG.md, cli/package.json, cli/src/publish.ts, cli/yarn.lock
- Refs https://github.com/microsoft/vscode-vsce/pull/791
- Refs https://github.com/felipecrs/semantic-release-vsce/pull/372
=> Migrate from deprecated `vsce` to `@vscode/vsce`

webui/package.json, webui/src/pages/extension-list/extension-list.tsx
Fixes #650
Fixes #608
Set `hasMore` to `false`, so that `loadMore` function isn't called while loading more results
=> Search via UI omits second page of ten search results

.gitpod.dockerfile, server/build.gradle, server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java, server/src/test/java/org/eclipse/openvsx/TestSearchConfig.java
Fixes #651
Make extensionId field case insensitive
Update ElasticSearch to 7.11.0
- Open this PR in Gitpod
- Search for `REDHAT.vscode-YaMl` using the webui, it should return the same result(s) as `redhat.vscode-yaml`.
- Try out different queries.
- Try out different ways of searching, e.g. using VSCode.
=> Search should not be case sensitive

webui/src/pages/user/generate-token-dialog.tsx, webui/src/pages/user/user-settings-tokens.tsx
This PR does the following:
- it prevents you from accidentally creating tokens by hitting <kbd>Enter</kbd> when on the page with the create modal closed
- it disabled the <kbd>Delete</kbd> buttons while deleting another one to prevent deleting the same token twice and getting an error
=> Access token dialog improvements

webui/src/pages/admin-dashboard/namespace-input.tsx, webui/src/pages/extension-list/extension-list-header.tsx, webui/src/pages/extension-list/extension-list-searchfield.tsx
Makes the search bar more accessible as well as enabling subsequent keyboard navigation for the sorting toggle
=> Search bar improvements

server/src/main/java/org/eclipse/openvsx/AdminAPI.java, server/src/main/java/org/eclipse/openvsx/AdminService.java, server/src/main/java/org/eclipse/openvsx/json/ChangeNamespaceJson.java, server/src/test/java/org/eclipse/openvsx/AdminAPITest.java, webui/src/extension-registry-service.ts, webui/src/pages/admin-dashboard/namespace-admin.tsx, webui/src/pages/admin-dashboard/namespace-change-dialog.tsx, webui/src/pages/user/user-namespace-member-list.tsx, webui/src/pages/user/user-settings-namespace-detail.tsx
Fixes #427
Added change namespace dialog to the webui
Added `/admin/change-namespace` endpoint to server
- Navigate to admin dashboard
- Search for a namespace
- Click the 'Change namespace' button
- A dialog opens up
- Type a new namespace name and check/uncheck the options
- Click the 'Change namespace' button in the dialog to perform the operation
=> [Admin] Add Ability to Change Namespace

server/src/main/java/org/eclipse/openvsx/UpstreamProxyService.java, server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java, server/src/main/java/org/eclipse/openvsx/adapter/UpstreamVSCodeService.java
Fixes #452
Added UpstreamProxyService
- Add to `dev/application.properties`:
```
ovsx:
upstream:
proxy:
enabled: true
url: https://open-vsx.org/
```
- Run the server
- Test the upstream endpoints
- Expected result: all `open-vsx.org` links are rewritten to `localhost:8080`
=> Add a way to proxy upstream requests instead of external links

server/src/main/java/org/eclipse/openvsx/migration/ExtractResourcesJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/migration/FixTargetPlatformsJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/migration/FixTargetPlatformsService.java, server/src/main/java/org/eclipse/openvsx/migration/MigrationRunner.java, server/src/main/java/org/eclipse/openvsx/migration/RenameDownloadsJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/migration/SetPreReleaseJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/resources/db/migration/V1_34__ExtensionVersion_Fix_TargetPlatform.sql, server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
Fixes #580 
Added FixTargetPlatformMigration
Remove extensionFile at end of a migration
Don't run migrations in mirror mode
- Open this PR in Gitpod, let the workspace initialize
- Stop the server
- using the `psql` command, execute:
```
SELECT n.name, e.name, ev.version, ev.target_platform
FROM extension_version ev
JOIN extension e ON e.id = ev.extension_id
JOIN namespace n ON n.id = e.namespace_id
WHERE ev.target_platform <> 'universal';
```
- copy-paste the output to a file
- then set all target platforms to 'universal' using the `psql` command:
```
UPDATE extension_version SET target_platform = 'universal';
```
- and execute the 1.34 migration script:
```
INSERT INTO migration_item(id, migration_script, entity_id, migration_scheduled)
SELECT nextval('hibernate_sequence'), …
```
=> Corrupted metadata extension in some extensions regarding targetPlatform

doc/development.md, server/src/dev/resources/static/documents/publisher-agreement.md
Currently copy-pasting some commands with smart quotes results in errors.
Replace all the smart quotes with straight quotes for consistency.
Signed-off-by: David Xia <david@davidxia.com>
=> fix docs: only use straight quotes

server/src/main/java/org/eclipse/openvsx/migration/OrphanNamespaceMigration.java, server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java, server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java, server/src/main/java/org/eclipse/openvsx/search/ISearchService.java, server/src/main/java/org/eclipse/openvsx/search/RelevanceService.java, server/src/main/java/org/eclipse/openvsx/search/SearchUtilService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountProcessor.java
Fixes #707 
Decreased transaction scope by creating `RelevanceService.toSearchEntryTrxn`
Added `updateSearchEntriesAsync` to do multiple concurrent index queries.
=> Download count update partition ElasticSearch search entries update

server/src/main/java/org/eclipse/openvsx/migration/ExtensionVersionSignatureJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/migration/GenerateKeyPairJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/migration/GenerateKeyPairJobService.java
Use smaller transactions in `GenerateKeyPairJobRequestHandler`.
Evict caches before persisting signature `FileResource`.
=> Release v0.11.0 fixes

cli/package.json
When trying to publish a package to open-vsx after installing `ovsx` via the command `npm i -g @vscode/vsce ovsx`, the package cannot seem to find the `semver` dependency. It's a transitive dependency from `@vscode/vsce` but explicitly used in the ovsx code.
This led to a failure in our deployment pipeline, see [here](https://github.com/langium/langium/actions/runs/4861701176/jobs/8667062213#step:7:45).
This PR adds the `semver` package explicitly, so that this issue doesn't occur anymore.
=> Add `semver` dependency to the `ovsx` package

webui/src/main.tsx, webui/src/pages/extension-list/extension-list-searchfield.tsx
fix #660 
I modified the theme colour of the search icon, now it looks like this:
|          | light mode  | dark mode |
| ------------- | ------------- | ------------- |
unhovered | <img width="859" alt="image" src="https://user-images.githubusercontent.com/108029327/234316510-d039f627-e5ed-4448-88f9-47b291b9527a.png">  | <img width="847" alt="image" src="https://user-images.githubusercontent.com/108029327/234318089-35e24c22-e89e-4c22-9d4e-cab34fcf2ce5.png">  |
hovered | <img width="832" alt="image" src="https://user-images.githubusercontent.com/108029327/234317636-7bbd38c4-48fd-478f-ba04-ffb9ec1531c9.png"> | <img width="837" alt="image" src="https://user-images.githubusercontent.com/108029327/234318265-1a4ac6d5-3985-466d-b879-68db3b74e0ab.png">
=> fix search icon contrast issues

server/src/main/java/org/eclipse/openvsx/RegistryAPI.java, server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java, server/src/main/java/org/eclipse/openvsx/json/QueryParamJson.java, server/src/main/java/org/eclipse/openvsx/json/SearchEntryJson.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
Fixes #795 
Lower amount of entries in `allVersions` map to 100. 
Change default size for `/api/-/query` and `/api/v2/-/query` to 100
=> Lower allVersions and default response size from 200 items to 100 items

doc/development.md
Update `doc/development.md` to match the settings of elastic search with the one for `gitpod` settings under `.gitpod.yml`.
Without these settings the `openvsx` server would exit with an exception as credentials for elastic search are missing.
=> Update development documentation for elastic search

server/src/main/java/org/eclipse/openvsx/ExtensionService.java, server/src/main/java/org/eclipse/openvsx/UrlConfigService.java, server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdDailyUpdateJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdNewExtensionJobRequest.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdNewExtensionJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdService.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdUpdateService.java, server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionHandler.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionJooqRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/NamespaceJooqRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java, server/src/main/java/org/eclipse/openvsx/util/BuiltInExtensionUtil.java, server/src/main/resources/db/migration/V1_43__Defer_Public_Id_Unique_Constraint.sql, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeIdUpdateServiceTest.java, server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
Fixes #819 
Add public_id synchronization
Add tests
Add config property to update on start
=> Fix "unique_extension_public_id" unique constraint violation

server/build.gradle, server/src/dev/resources/application.yml, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/RegistryAPI.java, server/src/main/java/org/eclipse/openvsx/RegistryApplication.java, server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java, server/src/main/java/org/eclipse/openvsx/metrics/MetricsConfiguration.java, server/src/main/java/org/eclipse/openvsx/metrics/RegistryObservationConvention.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionJooqRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java, server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java, server/src/main/java/org/eclipse/openvsx/search/ISearchService.java, server/src/main/java/org/eclipse/openvsx/search/SearchUtilService.java
Configure tracing
Add `@Observed` for more detailed observation
Add loki4j for log indexing
Add OpenTelemetry resource attributes
=> Configure tracing

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
**Description**
Fixes: #780 
The commit fixes an issue when respecting `sortBy` and `sortOder`. The proper ordering provided by the search-hits were not respected when collecting them after being streamed.
=> server: fix `sortBy` and `sortOrder`

server/src/dev/resources/application.yml, server/src/main/java/org/eclipse/openvsx/IExtensionRegistry.java, server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/RegistryAPI.java, server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java, server/src/main/java/org/eclipse/openvsx/json/RegistryVersionJson.java, webui/src/default/default-app.tsx, webui/src/default/page-settings.tsx, webui/src/extension-registry-service.ts, webui/src/extension-registry-types.ts
**Server:**
* Define server version in gradle.properties
* Add gradle task to create a resources properties file in the build directory
* Expose server version at the endpoint: /api/version
**Web-ui:**
* Display the server version in the footer.
Fixes #21
=> Expose version of the registry service via API endpoint

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/admin/AdminService.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionJooqRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java, server/src/test/java/org/eclipse/openvsx/admin/AdminAPITest.java, server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
Get file urls in one query
Find latest versions for user
=> Get file urls in one query

server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/admin/AdminService.java, server/src/main/java/org/eclipse/openvsx/eclipse/EclipseService.java, server/src/main/java/org/eclipse/openvsx/eclipse/PublisherComplianceChecker.java, server/src/test/java/org/eclipse/openvsx/eclipse/EclipseServiceTest.java
- Use public profile when checking Eclipse publisher agreement
- Use public profile when checking if publisher is compliant
- Add testGetPublicProfile unit test back in
=> Use public profile

server/src/main/java/org/eclipse/openvsx/migration/ExtensionVersionSignatureJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/publish/ExtensionVersionIntegrityService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtil.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
Create signature ZIP archive
Signature renew: minimize down-time between old and new signature
=> Create signature ZIP archive

webui/src/pages/extension-list/extension-list.tsx
The search input field on the open-vsx.org is not debounced. So, for example, if I rapidly type "123456" into the search field and add a debug log for the requests sent by the page, I see a separate query sent for each character:
There is, however, code present for debouncing the sending of new searches and aborting old requests. It's just not run at the correct time. I believe the empty useEffect dependency list (removed in this MR) was an accidental mistake. Without that empty list, the debounce behavior appears correct; the useEffect callback cancels all but the last search within the debounce period. Only the final query is sent to the server.
=> Debounce webui search

webui/package.json, webui/src/main.tsx, webui/src/pages/admin-dashboard/extension-admin.tsx, webui/src/pages/admin-dashboard/extension-remove-dialog.tsx, webui/src/pages/admin-dashboard/extension-version-container.tsx, webui/src/pages/admin-dashboard/namespace-admin.tsx, webui/src/pages/admin-dashboard/namespace-change-dialog.tsx, webui/src/pages/admin-dashboard/publisher-admin.tsx, webui/src/pages/admin-dashboard/publisher-revoke-dialog.tsx, webui/src/pages/extension-detail/extension-detail-changes.tsx, webui/src/pages/extension-detail/extension-detail-overview.tsx, webui/src/pages/extension-detail/extension-detail-reviews.tsx, webui/src/pages/extension-detail/extension-detail.tsx, webui/src/pages/extension-detail/extension-review-dialog.tsx, webui/src/pages/extension-list/extension-list-item.tsx, webui/src/pages/extension-list/extension-list.tsx, webui/src/pages/namespace-detail/namespace-detail.tsx, webui/src/pages/user/add-namespace-member-dialog.tsx, webui/src/pages/user/avatar.tsx, webui/src/pages/user/create-namespace-dialog.tsx, webui/src/pages/user/generate-token-dialog.tsx, webui/src/pages/user/publish-extension-dialog.tsx, webui/src/pages/user/user-namespace-details.tsx, webui/src/pages/user/user-namespace-extension-list-item.tsx, webui/src/pages/user/user-namespace-extension-list.tsx, webui/src/pages/user/user-namespace-member-list.tsx, webui/src/pages/user/user-publisher-agreement.tsx, webui/src/pages/user/user-settings-extensions.tsx, webui/src/pages/user/user-settings-namespaces.tsx, webui/src/pages/user/user-settings-tokens.tsx
- Fix extension list debounce
- Keep abortController between re-renders
- Bump webui to 0.11.8
=> Fix extension list debounce

server/src/main/java/org/eclipse/openvsx/mirror/MirrorExtensionService.java
Since the signature format has been updated in PR #928, the mirror needs to update its logic for signature validation when mirroring extensions from upstream. With this commit, now the mirror will extract the signature zip file and look for the signature, then use this signature to validate the vsix.
Fixes #938.
=> Update signature validation logic

server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java, server/src/main/java/org/eclipse/openvsx/ExtensionService.java, server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java, server/src/main/java/org/eclipse/openvsx/migration/CheckPotentiallyMaliciousExtensionVersionsService.java, server/src/main/java/org/eclipse/openvsx/migration/MigrationRunner.java, server/src/main/java/org/eclipse/openvsx/migration/PotentiallyMaliciousJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/publish/PublishExtensionVersionHandler.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionJooqRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/jooq-gen/org/eclipse/openvsx/jooq/tables/ExtensionVersion.java, server/src/main/jooq-gen/org/eclipse/openvsx/jooq/tables/records/ExtensionVersionRecord.java, server/src/main/resources/db/migration/V1_46__ExtensionVersion_PotentiallyMalicious.sql, server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
This commit enforces that only extension versions compliant with the publisher agreement can be published.
Already existing extensions versions are checked as part of a migration job.
Contributed on behalf of STMicroelectronics
=> feat: add publisher agreement compliance check

server/build.gradle, server/src/dev/resources/application.yml
Use Jetty instead of Tomcat so that requests no longer get queued and the server remains responsive under all conditions. 
It also logs an error, which makes monitoring easier.
source: https://blog.qaware.de/posts/java-service-queues/#jetty-server
=> Replace Tomcat with Jetty

server/build.gradle
Update Spring Boot to 3.2.2 for Jetty connection idle timeout fix [spring-projects/spring-boot#38960](https://github.com/spring-projects/spring-boot/issues/38960)
=> Update to Spring Boot 3.2.2

server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java, server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
Count vscode asset endpoint calls
Count api file endpoint calls
=> FileResource usage metrics

webui/package.json, webui/src/extension-registry-service.ts
Add `AdminServiceConstructor`, so that implementing type can be passed as a parameter and `ExtensionRegistryService` (this) can be passed into the `AdminServiceConstructor`.
=> Add AdminServiceConstructor

server/src/main/java/org/eclipse/openvsx/web/ServerErrorController.java
=> Add ServerErrorController

server/src/main/java/org/eclipse/openvsx/extension_control/ExtensionControlService.java, server/src/main/java/org/eclipse/openvsx/migration/FixTargetPlatformsService.java, server/src/main/java/org/eclipse/openvsx/mirror/DataMirrorService.java, server/src/main/resources/db/migration/V1_49__System_User.sql
Use `"system"` as user data provider, because `null` values are treated as distinct values, making it possible to insert multiple user data rows with the same login name and `null` as provider.
=> Add system provider for users

server/src/main/java/org/eclipse/openvsx/adapter/VSCodeAPI.java
=> Add getLatest endpoint

server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java, server/src/main/java/org/eclipse/openvsx/adapter/WebResourceService.java, server/src/main/java/org/eclipse/openvsx/cache/CacheService.java, server/src/main/java/org/eclipse/openvsx/cache/ExpiredFileListener.java, server/src/main/java/org/eclipse/openvsx/cache/FilesCacheKeyGenerator.java, server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java, server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/IStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/LocalStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java, server/src/main/resources/ehcache.xml, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java
Add User-Agent to AzureBlobStorageService
Serve resources from extension package
=> Serve resource files on demand

server/src/main/java/org/eclipse/openvsx/entities/AdminStatistics.java, server/src/main/java/org/eclipse/openvsx/entities/AzureDownloadCountProcessedItem.java, server/src/main/java/org/eclipse/openvsx/entities/Extension.java, server/src/main/java/org/eclipse/openvsx/entities/ExtensionReview.java, server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java, server/src/main/java/org/eclipse/openvsx/entities/FileResource.java, server/src/main/java/org/eclipse/openvsx/entities/MigrationItem.java, server/src/main/java/org/eclipse/openvsx/entities/Namespace.java, server/src/main/java/org/eclipse/openvsx/entities/NamespaceMembership.java, server/src/main/java/org/eclipse/openvsx/entities/PersistedLog.java, server/src/main/java/org/eclipse/openvsx/entities/PersonalAccessToken.java, server/src/main/java/org/eclipse/openvsx/entities/SemanticVersion.java, server/src/main/java/org/eclipse/openvsx/entities/SignatureKeyPair.java, server/src/main/java/org/eclipse/openvsx/entities/UserData.java, server/src/main/java/org/eclipse/openvsx/json/BadgeJson.java, server/src/main/java/org/eclipse/openvsx/json/ChangeNamespaceJson.java, server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java, server/src/main/java/org/eclipse/openvsx/json/ExtensionReferenceJson.java, server/src/main/java/org/eclipse/openvsx/json/ExtensionReplacementJson.java, server/src/main/java/org/eclipse/openvsx/json/NamespaceDetailsJson.java, server/src/main/java/org/eclipse/openvsx/json/SearchEntryJson.java, server/src/main/java/org/eclipse/openvsx/json/UserJson.java, server/src/main/java/org/eclipse/openvsx/json/VersionReferenceJson.java, server/src/main/java/org/eclipse/openvsx/json/VersionTargetPlatformsJson.java, server/src/main/java/org/eclipse/openvsx/search/ExtensionSearch.java, server/src/main/java/org/eclipse/openvsx/security/CodedAuthException.java, server/src/main/java/org/eclipse/openvsx/security/IdPrincipal.java, server/src/main/java/org/eclipse/openvsx/util/ErrorResultException.java, server/src/main/java/org/eclipse/openvsx/util/NotFoundException.java, server/src/test/java/org/eclipse/openvsx/MockTransactionTemplate.java
- Fields in a "Serializable" class should either be transient or serializable
- Make entity fields private
- Add serialVersionUID
=> Serializable class fields

server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/UserService.java, server/src/main/java/org/eclipse/openvsx/admin/ChangeNamespaceJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/admin/ChangeNamespaceService.java, server/src/main/java/org/eclipse/openvsx/cache/CacheService.java, server/src/main/java/org/eclipse/openvsx/storage/AwsStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/IStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/LocalStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java, server/src/main/java/org/eclipse/openvsx/util/NamingUtil.java, webui/src/pages/user/user-namespace-details.tsx
Fixes #1064 
Rename and copy namespace logo
Remove cached namespace details
Improve namespace detail form UX
=> Fix change namespace action

.devfile.yaml, .vscode/extensions.json, README.md, doc/development.md, openshift/README.md, openshift/application.yml, openshift/cli.Dockerfile, openshift/extensions.txt, openshift/openvsx-deployment.yml, openshift/openvsx.Dockerfile, openshift/scripts/publish_extensions.sh, webui/src/default/default-app.tsx
This PR introduces a `.devfile.yaml` that sets up a complete development environment in Eclipse Che for developing, testing, and running OpenVSX.
Watch the screencast to see how it works:
[Run_in_Che.webm](https://github.com/user-attachments/assets/5e3caba1-24dd-4ad1-8d86-8d720e8d231f)
The PR also includes a deployment configuration for OpenShift, enabling the deployment and operation of a custom OpenVSX registry on OpenShift. Additionally, it provides the capability to patch Eclipse Che, allowing it to seamlessly integrate and use this custom registry. 
Watch the screencast to see how it works:
[Deploy_on_OpenShift.webm](https://github.com/user-attachments/assets/ecec82dd-d27a-46aa-9d31-cc64df1a17cc)
A new badge has been added to the main README.md, providing a direct link to open the …
=> feat: Add configuration for OpenShift deployment and Eclipse Che development

server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/UserService.java
=> Fix GHSA-wc7c-xq2f-qp4h

CONTRIBUTING.md, README.md, webui/src/default/menu-content.tsx
=> Replace links to Gitter with link to Slack workspace

server/src/main/java/org/eclipse/openvsx/adapter/WebResourceService.java, server/src/main/java/org/eclipse/openvsx/cache/ExpiredFileListener.java, server/src/main/java/org/eclipse/openvsx/cache/FilesCacheKeyGenerator.java, server/src/main/java/org/eclipse/openvsx/storage/AwsStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java, server/src/main/resources/ehcache.xml, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java, server/src/test/java/org/eclipse/openvsx/storage/AzureBlobStorageServiceTest.java
Use generated file name to prevent orphaned files when multiple requests get the same uncached file at the same time.
=> Use generated file name for file caching

server/src/main/java/org/eclipse/openvsx/adapter/WebResourceService.java, server/src/main/java/org/eclipse/openvsx/storage/AwsStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/IStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java, server/src/main/java/org/eclipse/openvsx/util/FileUtil.java
Synchronize resource file writing in case the cache is empty and multiple requests try to write to the same file path simultaneously.
=> Synchronize resource file writing

server/build.gradle, server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java, server/src/main/java/org/eclipse/openvsx/adapter/WebResourceService.java, server/src/main/java/org/eclipse/openvsx/cache/FilesCacheKeyGenerator.java, server/src/test/java/org/eclipse/openvsx/IntegrationTest.java
- Differentiate between `null` and `universal` target platform. `UrlUtil.getFileApiUrl` treats `universal` as `null` and excludes it from the url.
- Make namespace and extension names case insensitive, same as in the database.
- Pass `targetPlatform` when evicting webresource file.
=> Improve file cache key

server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/UserService.java, server/src/main/java/org/eclipse/openvsx/security/OAuth2UserServices.java, server/src/main/java/org/eclipse/openvsx/security/SecurityConfig.java, server/src/main/java/org/eclipse/openvsx/security/TokenService.java, server/src/main/java/org/eclipse/openvsx/web/WebConfig.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java, webui/src/context.ts, webui/src/default/menu-content.tsx, webui/src/extension-registry-service.ts, webui/src/main.tsx, webui/src/pages/admin-dashboard/admin-dashboard.tsx, webui/src/pages/user/user-settings.tsx
This pull request introduces several changes to enable and check OAuth2 support in the application. The key changes include adding methods to check OAuth2 status, modifying the security configuration, and updating the web UI to reflect OAuth2 status.
In case when OAuth2 is not configured **Publish** and **Log In** buttons are hidden and we have like readonly mode:
**Related issue:** https://github.com/eclipse/openvsx/issues/1041
**Web version:**
**Mobile version:**
**What I did to test how it works**
1. Remove from **openvsx/server/src/dev/resources/application.yml** this block:
```
security:
oauth2:
client:
registration:
eclipse:
authorization-grant-type: authorization_code
redirect-uri: http://localhost/login/oauth2/code/eclipse
scope: openvsx_publisher_agreement, profile
provider: …
```
=> feat: make OAuth2 configuration optional

server/src/main/java/org/eclipse/openvsx/storage/AzureDownloadCountService.java
userAgentHeader could be optional, but it should be set at least when the registry makes a request with `User-Agent: OpenVSX`.
=> Check that userAgentHeader is set

server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java, server/src/main/java/org/eclipse/openvsx/adapter/VSCodeIdUpdateService.java, server/src/main/java/org/eclipse/openvsx/adapter/WebResourceService.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionJooqRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionJooqRepository.java, server/src/main/java/org/eclipse/openvsx/storage/AwsStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java, server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java
(Java) Parentheses should be removed from a single lambda parameter when its type is inferred
=> (Java) Parentheses should be removed

webui/src/pages/admin-dashboard/admin-dashboard.tsx, webui/src/pages/admin-dashboard/extension-remove-dialog.tsx, webui/src/pages/admin-dashboard/namespace-admin.tsx, webui/src/pages/admin-dashboard/publisher-admin.tsx, webui/src/pages/extension-detail/extension-detail-overview.tsx, webui/src/pages/user/user-namespace-extension-list-item.tsx, webui/src/pages/user/user-publisher-agreement.tsx, webui/src/pages/user/user-settings-namespaces.tsx, webui/src/pages/user/user-settings-profile.tsx
(TypeScript) Ternary operators should not be nested
=> Nested ternary operations

server/Dockerfile
This should fix this [issue](https://github.com/eclipse/openvsx/actions/runs/13437413452/job/37542987642#step:10:39): `ERROR: failed to solve: unexpected key 'env' in 'env=DEVELOCITY_ACCESS_KEY'`.
This happens because GHA isn't using the latest dockerfile syntax yet, which is fixed by the `# syntax=docker/dockerfile:1` line. This is also documented in [Docker GHA secrets docs](https://docs.docker.com/build/ci/github-actions/secrets/), which I missed when I opened the initial PR https://github.com/eclipse/openvsx/pull/1091.
=> Dockerfile fix for Develocity access key

server/Dockerfile, server/gradle.properties
Enabled caching by default by specifying it in the root gradle.properties file. I also enabled filesystem watching and parallel execution by default, which often improves performance.
Since I tested this locally and I have caching enabled by default in my `$GRADLE_USER_HOME/gradle.properties` I didn't notice that the open vsx server project doesn't - this will fix it.
=> Enabled caching by default

server/src/main/java/org/eclipse/openvsx/RegistryApplication.java, server/src/main/java/org/eclipse/openvsx/UserAPI.java, server/src/main/java/org/eclipse/openvsx/UserService.java, server/src/main/java/org/eclipse/openvsx/json/LoginProvidersJson.java, server/src/main/java/org/eclipse/openvsx/security/CodedAuthException.java, server/src/main/java/org/eclipse/openvsx/security/OAuth2AttributesConfig.java, server/src/main/java/org/eclipse/openvsx/security/OAuth2AttributesMapping.java, server/src/main/java/org/eclipse/openvsx/security/OAuth2UserServices.java, server/src/main/java/org/eclipse/openvsx/security/SecurityConfig.java, server/src/main/java/org/eclipse/openvsx/web/WebConfig.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/UserAPITest.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java, server/src/test/java/org/eclipse/openvsx/admin/AdminAPITest.java, server/src/test/java/org/eclipse/openvsx/cache/CacheServiceTest.java, server/src/test/java/org/eclipse/openvsx/web/SitemapControllerTest.java, webui/package.json, webui/src/context.ts, webui/src/default/login.tsx, webui/src/default/menu-content.tsx, webui/src/extension-registry-service.ts, webui/src/extension-registry-types.ts, webui/src/main.tsx, webui/src/pages/admin-dashboard/admin-dashboard.tsx, webui/src/pages/user/user-settings.tsx
Replace the references to `OAuth2User` by `AuthUser`. This allows downstream extenders to more easily contribute alternative OAuth2 providers: If the expected data is stored in different attributes it will be possible to bridge it by implementing the proper `AuthUser`.
New configuration example:
```yml
ovsx:
oauth2:
provider: gitlab
attribute-names:
gitlab:
avatar-url: avatar_url
email: email
full-name: name
login-name: username
provider-url: '' # idk what this is for
spring:
security:
oauth2:
client:
registration:
gitlab:
client-id: [client-id]
client-secret: [client-secret]
authorization-grant-type: authorization_code
redirect-uri: http://[openvsx-host-name]/login/oauth2/code/gitlab
scope: read_user
clientName: OpenVSX
provider:
gitlab:
authorization-uri: …
```
=> server: refactor: introduce `AuthUser` interface

server/src/main/java/org/eclipse/openvsx/admin/AdminAPI.java, server/src/main/java/org/eclipse/openvsx/admin/AdminService.java, server/src/main/java/org/eclipse/openvsx/admin/ChangeNamespaceJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/repositories/PersonalAccessTokenJooqRepository.java, server/src/main/java/org/eclipse/openvsx/repositories/RepositoryService.java, server/src/main/java/org/eclipse/openvsx/util/FileUtil.java, server/src/test/java/org/eclipse/openvsx/admin/AdminAPITest.java, server/src/test/java/org/eclipse/openvsx/repositories/RepositoryServiceSmokeTest.java
- Added support for token to `/admin/namespace/{namespaceName}/members`
- Added support for token to `/admin/namespace/{namespaceName}/change-member`
- Use `useAccessToken` method so that `accessedTimestamp` gets updated
- Bugfix: access `synchronizedMap` within `synchronized` block
- Fix unit tests
=> Automate namespace claim process

server/src/main/java/org/eclipse/openvsx/eclipse/EclipseService.java, server/src/main/java/org/eclipse/openvsx/eclipse/PublisherComplianceChecker.java, server/src/main/java/org/eclipse/openvsx/migration/OrphanNamespaceMigration.java, server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java, server/src/main/java/org/eclipse/openvsx/storage/StorageMigration.java
Format specifiers should be used instead of string concatenation.
=> Use format specifiers

webui/src/components/text-divider.tsx, webui/src/pages/extension-detail/extension-detail.tsx
Fixes #1241 
Use `theme.palette.getContrastText`, so that text is always legible.
=> Extension header styling

server/build.gradle, server/src/main/java/org/eclipse/openvsx/migration/GenerateKeyPairJobRequestHandler.java, server/src/main/java/org/eclipse/openvsx/search/DatabaseSearchService.java, server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java, server/src/main/java/org/eclipse/openvsx/security/SecurityConfig.java, server/src/test/java/org/eclipse/openvsx/IntegrationTest.java, server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java, server/src/test/java/org/eclipse/openvsx/UserAPITest.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java, server/src/test/java/org/eclipse/openvsx/adapter/VSCodeIdUpdateServiceTest.java, server/src/test/java/org/eclipse/openvsx/admin/AdminAPITest.java, server/src/test/java/org/eclipse/openvsx/admin/AdminStatisticsJobRequestHandlerTest.java, server/src/test/java/org/eclipse/openvsx/eclipse/EclipseServiceTest.java, server/src/test/java/org/eclipse/openvsx/publish/ExtensionVersionIntegrityServiceTest.java, server/src/test/java/org/eclipse/openvsx/search/DatabaseSearchServiceTest.java, server/src/test/java/org/eclipse/openvsx/search/ElasticSearchServiceTest.java, server/src/test/java/org/eclipse/openvsx/storage/AzureBlobStorageServiceTest.java, server/src/test/java/org/eclipse/openvsx/web/SitemapControllerTest.java
- Fix tests
- Let Spring determine version of `org.apache.httpcomponents.client5:httpclient5`
- Fix `SearchHitsImpl` instance creation
- Replace ant matcher with path matcher
- Only throw `IllegalArgumentException` if `ovsx.integrity.key-pair` has a value
=> Update Spring Boot to 3.5.3
